### ISSUE TITLE
V2 api returns 500 for random accounts

### ISSUE THREAD

**Issue by Downy** [SunDwarf/OWAPI#10]
The v2 api seems to dislike certain people and doesn't return their stats.
For example;
https://owapi.net/api/v2/u/letsjoe-1228/stats

I've had people reporting this before but I didn't think of writing down those accounts.
It also only seems to happen to US based accounts, but I can't say that's the case with 100% certainty.

**Comment by SunDwarf** [comment]
Happens for people with over 1000 games.

**Comment by Downy** [comment]
Ah, so that's the cause. Got it.

**Comment by SunDwarf** [comment]
Fixed on the live version too.
