### ISSUE TITLE
Winrate calculation is wrong.

### ISSUE THREAD

**Issue by FuglyShmugly** [SunDwarf/OWAPI#101]
Somebody forgot about DRAWs. Found out while making a leaderboard for my community.

**Comment by azah** [comment]
**Blizzard** forgot about Draws. We also have to calculate losses manually, by subtracting games won from total games, because Blizzard hates negative stats.

**Comment by FuglyShmugly** [comment]
Wait what. How did I manage to get draws if i calculate them:

`draws = games - (wins+losses)`

**Comment by SunDwarf** [comment]
PRs welcome.

As for why it doesn't exist, I haven't played the game in a *long* time, and I've never actually seen a draw myself.

**Comment by azah** [comment]
So it's there but hidden? Ffs. 

I'll make a PR, @Sundwarf

**Comment by azah** [comment]
@FuglyShmugly Can you give me a username of someone with draws?

**Comment by FuglyShmugly** [comment]
@azah Foogley-2513 all of my 29 draws.

**Comment by azah** [comment]
Actually, Blizzard lists your losses as **207**. 178+29. 

I don't know what we can do, because there's no way to get that data from the page.

**Comment by azah** [comment]
Actually nevermind, apparently *Losses* and *Ties* are stored in another table on that page: *Miscellaneous*.

**Comment by FuglyShmugly** [comment]
I made a working page using your owapi with draws. Using the game_ stats games _ played games_ won and games _ lost

**Comment by azah** [comment]
@FuglyShmugly see #103. It will add `ties` & `losses` to `overall_stats` in `competitive` calls.
