### ISSUE TITLE
500 error on XBL Gamertag lookup

### ISSUE THREAD

**Issue by mrhazel** [SunDwarf/OWAPI#106]
## Issue

500 error when looking up the XBL gamertag `hootyQmcboob`

## Links that cause the issue

`https://owapi.net/api/v3/u/hootyQmcboob/stats?platform=xbl`

**Comment by azah** [comment]
XBL profiles don't have eliminations for comp stats? https://playoverwatch.com/en-us/career/xbl/hootyQmcboob

**Comment by azah** [comment]
????? @mrhazel your profile doesnt have those stats for some reason

Other xbl profiles have the stats: https://playoverwatch.com/en-us/career/xbl/Best%20Top%20NA
