### ISSUE TITLE
How can I translate time value.

### ISSUE THREAD

**Issue by Bacass** [SunDwarf/OWAPI#108]
Hello
My name is Lee WonWoo
I live in South Korea :)

I use your Overwatch Json Api
I have a question.

"objective_time": 0.37027777777777776,
"time_spent_on_fire": 0.33999999999999997,
"objective_time_most_in_game": 0.060000000000000005,
"objective_time_avg": 0.021666666666666667,
"objective_time": 7.751944444444445,
"time_spent_on_fire": 10.516944444444444,
"objective_time_most_in_game": 0.06472222222222222,

What does this number?
Is this the time value??

I want to translate 
HH:MM:SS

How can I translate 
X.XXXX    —>     HH:MM:SS

I wait your answer :)
Your api is very good. !
Thank you.

**Comment by SunDwarf** [comment]
Those times are in hours.

So to get the hours, minutes, and seconds, you would do something like this:

```
>>> seconds = time * 3600
>>> minutes, seconds = divmod(seconds, 60)
>>> hours, minutes = divmod(minutes, 60)
```
Where time is one of these numbers, for example 10.5169.
