### ISSUE TITLE
{"msg": "please report this!", "error": 500, "exc": "IndexError('list index out of range',)"}

### ISSUE THREAD

**Issue by authanram** [SunDwarf/OWAPI#114]
## Issue

https://owapi.net/api/v3/u/Norexxan-2402/blob => FAILED
{"msg": "please report this!", "error": 500, "exc": "IndexError('list index out of range',)"}

## Links that cause the issue

https://owapi.net/api/v3/u/Norexxan-2402/blob

**Comment by azah** [comment]
Exceptions on exceptions on exceptions. Nice, blizzard.

**Comment by SunDwarf** [comment]
Nah, this one is more of my fault. I didn't actually check if they had stats or not.
