### ISSUE TITLE
Some problems with server instance?

### ISSUE THREAD

**Issue by Lord-Protector** [SunDwarf/OWAPI#117]
## Issue

I very often get errors about redis and etc.

**Comment by azah** [comment]
`ReplyError('MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.',)`

will look into this

**Comment by Lord-Protector** [comment]
Yeah, thanks.

**Comment by SunDwarf** [comment]
i should start a funding drive for owapi.net or something

**Comment by SunDwarf** [comment]
not so fun fact: owapi has a memory leak somewhere that I haven't been bothered to fix
so my vps ran out of memory, fun!

**Comment by azah** [comment]
tbh it's not like you have to host it, if it's too much hassle to maintain personally I'd remove it. Setting it up is super easy anyhow

**Comment by SunDwarf** [comment]
it's only an issue because I use my vps for my discord stuff and owapi tends to get OOM'd first

there's two machines that are transparently proxied by nginx anyway so if one goes down the other one picks up the slack

**Comment by Lord-Protector** [comment]
Thanks for fast fix!

**Comment by nebyark** [comment]
First time I've encountered this issue, but I'm running into the same redis error response as above.
