### ISSUE TITLE
Refresh Issue

### ISSUE THREAD

**Issue by adriansmitto** [SunDwarf/OWAPI#118]
## Issue

I've been using the api to monitor my friends progress, and from the 7 players I monitor, ONE has a refresh issue, it seems to be stucked in the same stats forever.

This is the link
https://owapi.net/api/v2/u/Paip-1645/stats/competitive

And these are the real stats
http://masteroverwatch.com/profile/pc/us/Paip-1645

## Links that cause the issue

`https://owapi.net/api/v2/u/Paip-1645/stats/competitive`

Any ideas?

Regards

**Comment by SunDwarf** [comment]
Use the appropriate region, or upgrade to V3, which provides all region data.

The API uses EU stats by default - those are US stats.

https://owapi.net/api/v2/u/Paip-1645/stats/competitive?region=us

**Comment by adriansmitto** [comment]
Thank you very much. my bad :(
