### ISSUE TITLE
Could not find a version that satisfies the requirement Kyoukai>=2.0.0

### ISSUE THREAD

**Issue by briva** [SunDwarf/OWAPI#119]
## Issue

>   Could not find a version that satisfies the requirement Kyoukai>=2.0.0 (from -r requirements.txt (line 1)) (from versions: 1.7.2.linux-x86_64, 1.7.3.li
> nux-x86_64, 1.8.0.linux-x86_64, 1.8.0.1.linux-x86_64, 1.8.1.linux-x86_64, 1.8.2.linux-x86_64, 1.8.3.linux-x86_64, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.6.
> 0, 1.6.1, 1.7.0, 1.7.1, 1.8.4, 1.8.5, 1.8.6, 1.9.0, 1.9.1, 1.9.2, 1.9.2.post1, 1.9.2.1)                                                                  
> No matching distribution found for Kyoukai>=2.0.0 (from -r requirements.txt (line 1))

## Links that cause the issue

> (venv) g2brivael3@staging-stats:~/OWAPI$ pip install wheel && pip install -r requirements.txt
> Requirement already satisfied: wheel in /home/g2brivael3/.local/lib/python2.7/site-packages
> Collecting Kyoukai>=2.0.0 (from -r requirements.txt (line 1)

**Comment by SunDwarf** [comment]
This is because I haven't pushed Kyoukai 2.0.0 to PyPI yet.

Give me a sec.

**Comment by SunDwarf** [comment]
Uploaded - No guarentees this new version will work with the rewritten code, however.
