### ISSUE TITLE
/heroes is broken in 2 ways

### ISSUE THREAD

**Issue by azah** [SunDwarf/OWAPI#121]
## Issue

1. Currently visiting /heroes gives this error:

```json
{
    "exc": "TypeError('Route takes 1 args, passed in 0 instead',)",
    "msg": "please report this!",
    "error": 500
}
```

2. If you rename the function name to `__get_info`, it fixes the above problem, but then gives this problem:

```json
{
    "exc": "IndexError('list index out of range',)",
    "error": 500,
    "msg": "please report this!"
}
```

The error itself being in the parsing function:

```
File "/Users/andrew/Desktop/Sync/_programming/Python/OWAPI/owapi/v4/__init__.py", line 250, in __get_heroes

    heroes = parsing.bl_parse_all_heroes(parsed)

  File "/Users/andrew/Desktop/Sync/_programming/Python/OWAPI/owapi/v4/parsing.py", line 189, in bl_parse_all_heroes

    _hero_info = parsed.findall(".//div[@data-group-id='comparisons']")[0]

IndexError: list index out of range
```

## Links that cause the issue

`https://owapi.net/api/v3/heroes`

**Comment by SunDwarf** [comment]
I fixed the first error, but in order to fix the second error, the parsing routine for the heroes data would have to be rewritten.

It seemingly uses the same code that is used for parsing the heroes list of a specific user?
