### ISSUE TITLE
Does not return JSON when invalid battletag is used (PC only)

### ISSUE THREAD

**Issue by chesterhow** [SunDwarf/OWAPI#127]
## Issue

When an invalid battletag is used for pc platform, the response seems to be in html instead
![screen shot 2016-12-29 at 10 44 44 am](https://cloud.githubusercontent.com/assets/9312956/21535732/33e2d98c-cdb4-11e6-858e-86ffe2081cba.png)

## Links that cause the issue

```
https://owapi.net/api/v3/u/hello/blob?platform=pc
https://owapi.net/api/v3/u/hello-1234/blob?platform=pc
```

**Comment by SunDwarf** [comment]
wait, that broke it even more
