### ISSUE TITLE
inconsistency of dva keyword

### ISSUE THREAD

**Issue by briva** [SunDwarf/OWAPI#132]
Inconsistency about dva heroes.

Sometime "dva" is use :

Example :

> "eu": {
>     "heroes": {
>       "playtime": {
>         "quickplay": {
>           "dva": 0.45,
>         },
>         "competitive": {
>           ...
>           "dva": 4,
>         }
>       }

Sometimes "d.va"

Example :

> {
>   "eu": {
>     "heroes": {
>       "stats": {
>         "quickplay": {
>           "d.va": {

**Comment by SunDwarf** [comment]
It should only use `dva`. I'll fix this.

**Comment by briva** [comment]
Awesome 👍  So fast like always :)
