### ISSUE TITLE
Installing Issues

### ISSUE THREAD

**Issue by Domekologe** [SunDwarf/OWAPI#133]
## Issue

The errors from the API is a very funny one (I think): You are being ratelimited.
Yeah I know that comes when I Get the answer from the JSON multiple time.

At this place a big sorry for my english.

I tried it a multiple time to install the API on one of my virtual servers.
I tried it with Debian, Ubuntu and CentOS and everytime I got a another error.
And I must say, my linux knowledge is not so good to configure things extremely.

Can someone say me on which linux system it will be worked perfectly?

My last try was with Debian and I got this error:
Error: Command '['/******/venv/bin/python3.5', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1

And the Answers on other sites doesn't help

**Comment by Domekologe** [comment]
Now I can run it (after multiple reinstallations) but how can I connect with it? When I will connect to port 4444 I get an Connection failed error

**Comment by Domekologe** [comment]
OK, I solve it
I changes the ip address in owapi/app.py

**Comment by SunDwarf** [comment]
In the future, I would need the full error log when compiling if issues arise during installation.
