### ISSUE TITLE
Look like OWAPI died D:

### ISSUE THREAD

**Issue by Haskaalo** [SunDwarf/OWAPI#134]
I'm trying to request a user and it keep saying 404, even with others Battletag.

Also...

sorry for all these request on OWAPI.net with username trev... I'm trying things. :3

**Comment by SunDwarf** [comment]
What URL are you requesting?

**Comment by Haskaalo** [comment]
https://owapi.net/api/v2/u/Trev-11289/stats/competitive

**Comment by azah** [comment]
V2 is deprecated; use V3

**Comment by Haskaalo** [comment]
@azah , V3 is also not working :|

**Comment by Haskaalo** [comment]
Nevermind, V3 is working but V2 isn't working anymore.

**Comment by Haskaalo** [comment]
Also https://owapi.net/api/v3/u/Trev-11289/stats/competitive doesnt work anymore.

**Comment by SunDwarf** [comment]
Please read the API docs. That is not a valid V3 API url.

Additionally, V2 was removed very recently. I gave nearly 4 months notice before it was deprecated, and yet people still used it.

**Comment by azah** [comment]
Maybe we can bring /stats/competitive back?

**Comment by SunDwarf** [comment]
no thanks
