### ISSUE TITLE
Missing lifetime average energy for Zarya

### ISSUE THREAD

**Issue by gbigwood** [SunDwarf/OWAPI#136]
## Issue

Missing LIFETIME AVERAGE ENERGY for Zarya

## Links that cause the issue

`https://owapi.net/api/v3/u/ShadowHost-21615/heroes`

Thanks!

**Comment by Js41637** [comment]
I assume it's because it's the code considers it to be an Average stat which aren't included in the heroes view.

**Comment by gbigwood** [comment]
I can't see when using on any of: `stats` `heroes` `achievements` requests. I apologise if I have simply missed it.

**Comment by Js41637** [comment]
No, Average stats are included in `stats` endpoint but that doesn't include any hero specific average stats, only general average stats. There is no way to get average hero specific stats currently though it's an easy fix if @SunDwarf wants to make it.

**Comment by gbigwood** [comment]
I think I found what you are talking about here:
https://github.com/SunDwarf/OWAPI/blob/master/owapi/v3/parsing.py#L268

assuming that you are parsing from `playoverwatch.com`, you could change the logic to only skip the `tr` if the `th` was 'average`.

**Comment by Js41637** [comment]
That part of the code is checking if `average` is in the name of the stat includes the word average, not the specific box. If SunDwarf only wants to include hero specific averages a check will need to be added to ignore the average box or do what the other endpoints do and return an `average_stats: {}` value

**Comment by gbigwood** [comment]
awesome thanks!

**Comment by SunDwarf** [comment]
All heroes now have their server-side calculated `average_stats` key. This contains the key you requested, as well.

**Comment by Js41637** [comment]
dont forget da docs

**Comment by SunDwarf** [comment]
soon™
