### ISSUE TITLE
 asphalt: command not found

### ISSUE THREAD

**Issue by vexersa** [SunDwarf/OWAPI#137]
## Issue

I get this error : 
asphalt: command not found

After the step:

5. Start the OWAPI server.

PYTHONPATH=. asphalt run config.yml

## Links that cause the issue

Hi! Thank you for helping OWAPI by submitting an issue.
Before you submit, please make sure you've done the following:

* [x] Google/Search previous issues to make sure it hasn't been answered before.

Done.

* [ ] Ask if this is an *OWAPI* issue, or a *Linux* issue, etc.
    * OWAPI requires Python 3.5 or higher installed on a unix machine, and it's not really our job to troubleshoot random linux errors.

Thanks!

**Comment by bippum** [comment]
Make sure asphalt is installed and in your path.

**Comment by vexersa** [comment]
Thanks for the reply. I'm afraid this is where my knowledge of this
deployment gets a little spotty. Is asphalt a linux application? I have
searched but cannot seem to find it...

**Comment by SunDwarf** [comment]
Did you create a virtualenv and install the requirements?

**Comment by vexersa** [comment]
​Hi,

Yes, this command:

Install the requirements.

For debian-based systems: sudo apt install libxslt-dev python3-dev
build-essential zlib1g-dev
source ./venv/bin/activate && pip install wheel && pip install -r
requirements.txt

Produces this output:

(venv) andrew@domo:~$ Could not open requirements file: [Errno 2] No such
file or directory: 'requirements.txt'
Could: command not found

Where does the requirements.txt file need to be located?
​

**Comment by SunDwarf** [comment]
It's located in the directory you cloned `owapi` into.

**Comment by vexersa** [comment]
Alright,

Here is the output further:


Requirement already satisfied: wheel in ./venv/lib/python3.5/site-packages
Could not open requirements file: [Errno 2] No such file or directory:
'requirements.txt'
(venv) andrew@domo:~$ cd
(venv) andrew@domo:~$ ls
asphalt  OWAPI  venv
(venv) andrew@domo:~$ cd OWAPI/
(venv) andrew@domo:~/OWAPI$ ls
api.md               config.yml    LICENCE  rates.default.yml
 requirements.txt
config_noredis.yaml  CONTRIBUTORS  owapi    README.md

It appears to be there?

**Comment by SunDwarf** [comment]
Run `pip install -r requirements.txt` from that directory.

**Comment by vexersa** [comment]
​Great, thanks, that worked.

It appears that the server is now running. However, how do I access it from
something other than localhost? :)

P.S: Thanks for all your help. ​

**Comment by vexersa** [comment]
Alright, I understand that I missunderstood how the API works. For some
reason, I am unable to use the locally hosted service or I'm not sure how
to actually get it working correctly.

Regardless, is it possible to get per-hero stats? Eg:
https://owapi.net/api/v3/u/Dad-12262/heroes/ana ?

**Comment by azah** [comment]
@vexersa I do want to add per-hero stats to v3. It will happen sometime soon, I've been extremely busy lately.

**Comment by vexersa** [comment]
Awesome, that would be excellent.

What are your API rate limits currently per IP?
