### ISSUE TITLE
Display Season High

### ISSUE THREAD

**Issue by Nop0x** [SunDwarf/OWAPI#138]
## Issue

Should be pretty easy to encorporate the season high in the api as it's exposed by blizzard.

## Links that cause the issue

`https://owapi.net/api/v3/u/Nop0x-1146/blob`

**Comment by SunDwarf** [comment]
I can't see where it is defined inside the HTML.

**Comment by Js41637** [comment]
Yes blizzard doesn't say the season high on the website?

**Comment by azah** [comment]
Yea I don't see this. Not all of the stuff seen in-game is available on the website, such as stuff from last season.

**Comment by SunDwarf** [comment]
Closing this since it doesn't seem possible.
