### ISSUE TITLE
Error on render None and Bool type

### ISSUE THREAD

**Issue by briva** [SunDwarf/OWAPI#140]
Just build the last version and the response containing a None or Bool type are not json valid :

Example :

`{
	'kr': None,
	'us': None,
	'eu': None,
	'any': {
		'achievements': {
			'support': {
				'the_floor_is_lava': True,
				'rapid_discord': True,
				'the_iris_embraces_you': True,
				'huge_rez': True,
				'naptime': True,
				'supersonic': True,
				'huge_success': True,
				'group_health_plan': True,
				'enabler': True,
				'the_car_wash': True
			},`

**Comment by briva** [comment]
I re-test with a new installation on a other ubuntu version. And now i have other weird bug...

On all response, there is a "b'" just before the first json object and the response is imcomplete :/

Example :

`[b'{"us": {"stats": {"quickplay": {"average_stats": {"healing_done_avg": 179.0, "final_blows_avg": 6.89, "defensive_assists_avg": 0.0, "objective_kills_avg": 3.44, "eliminations_avg": 11.78, "objective_time_avg": 0.0061111111111111106, "offensive_assists_avg": 0.0, "damage_done_avg": 4733.0, "time_spent_on_fire_avg": 0.005277777777777778, "solo_kills_avg": 3.02, "melee_final_blows_avg": 0.06, "deaths_avg": 6.69}, "competitive": false, "game_stats": {"objective_time_most_in_game": 0.03444444444444445, "melee_final_blows": 22.0, "offensive_assist": 1.0, "defensive_assists_most_in_game": 7.0, "objective_time": 2.23, "environmental_deaths": 47.0, "solo_kills_most_in_game": 41.`

**Comment by SunDwarf** [comment]
Sorry, I fixed something but forgot to push it upstream. I'll have this resolved shortly.

**Comment by briva** [comment]
Thx man ;)
