### ISSUE TITLE
Potential issues w/ empty profiles

### ISSUE THREAD

**Issue by SunDwarf** [SunDwarf/OWAPI#142]
So certain users return empty profiles if the blizzard page exists but there's no data (this is an unintentional side effect).

I'm not sure what to do here:

 - Keep it as is, which returns a dict of empty dicts inside a region
 - Return `null` for the region as if it doesn't exist
 - Add a marker field that explains why it's empty

**Comment by Downy** [comment]
Personally I'd like the second option best. I'd wager most users of the api have a check for empty regions so this wouldn't require any additional effort on our side.

**Comment by jturbo26** [comment]
Agree with Downy. Null return would be best for my implementation.

**Comment by SunDwarf** [comment]
Most recent commit changes null semantics, which is a potentially breaking change.
