### ISSUE TITLE
Add rank img link

### ISSUE THREAD

**Issue by BleuDiamant** [SunDwarf/OWAPI#143]
Hi :)
Before write i want to congratulate you, your api is awesome :)
But i want to know if is possible to add the rank img link in the json result like this link 
https://blzgdapipro-a.akamaihd.net/game/rank-icons/season-2/rank-5.png

Thank for advance :)

(I actually developt a discord bot with many feature and i use your api to get overwatch stat it's ok ?)

**Comment by ptoast** [comment]
Hah, that's funny. I actually came here just now to make the exact same suggestion. I agree, it would be a nice quality of life feature to be able to grab a link to the rank icons from the json response.

**Comment by Downy** [comment]
I feel like this is something the end user should implement themselves, as this data is already exposed when using the `stats` endpoint.

**Comment by KingJP** [comment]
This can be closed due to commit #209 which added the rank image as "tier_image" in "overall_stats"
