### ISSUE TITLE
Data not refreshed?

### ISSUE THREAD

**Issue by calvinwankhede** [SunDwarf/OWAPI#144]
https://owapi.net/api/v3/u/Zorj-1865/blob

vs.

https://www.overbuff.com/players/pc/Zorj-1865

Just from the get-go, the returned data says that the player is only rank 38 whereas he is 142 on overbuff and masteroverwatch.

**Comment by SunDwarf** [comment]
To get the final level, you must do `(prestige * 100) + level`.

**Comment by calvinwankhede** [comment]
Oh, thank you, I'm not an OW player. Could you also tell me why is there a slight discrepancy in the ranks between the two?

**Comment by SunDwarf** [comment]
Region differences.
