### ISSUE TITLE
'list' object has no attribute 'findall'

### ISSUE THREAD

**Issue by Kezyma** [SunDwarf/OWAPI#145]
## Issue

Hi, I've been using your api for the last few weeks to retrieve stats for myself and the people I play with, today I noticed my db updater had been throwing null reference errors, so I went to a couple of URLs manually and it returned this:

{"msg": "please report this!", "exc": "AttributeError(\"'list' object has no attribute 'findall'\",)", "error": 500}

as it said to report it, I figured I probably should!

## Links that cause the issue

`http://owapi.net/api/v3/u/Kezyma-2202/blob`

**Comment by SunDwarf** [comment]
Test in production always works out.

Fixed.

**Comment by Kezyma** [comment]
Gosh, don't tell my boss you can fix things that quickly, or I might end up out of a job!

**Comment by SunDwarf** [comment]
I cheat slightly.

![1487876966](https://cloud.githubusercontent.com/assets/8783751/23274712/a1657b0e-f9fb-11e6-9ec7-747e7dd0ee47.png)
