### ISSUE TITLE
Arcade statistics

### ISSUE THREAD

**Issue by GalPressman** [SunDwarf/OWAPI#146]
Hello,
Is there a way to access arcade stats?
I can't seem to find it anywhere currently.

**Comment by azah** [comment]
Are those stats available on your blizzard web profile?

**Comment by Js41637** [comment]
There is no way to view arcade stats, Overwatch does not display them ingame or on the website.

**Comment by GalPressman** [comment]
Thanks for the comment, I'm closing the issue.
