### ISSUE TITLE
Orisa's stats parsing differently

### ISSUE THREAD

**Issue by LeafyDev** [SunDwarf/OWAPI#149]
## Issue

For certain BattleTags Orisa's stats are ordered the same way as other heroes (`eliminations` in `general_stats`) however for others `eliminations` / `weapon_accuracy` / `damage_done` and others are in `hero_stats`...

## Links that cause the issue

(Surround the links with backticks. Use triple backticks for multiple lines.)

`https://owapi.net/api/v3/u/KurwaClown-2905/heroes?platform=pc` => most of the info is in `general_stats` like other heroes.
`https://owapi.net/api/v3/u/SpiritWulf-21169/heroes?platform=pc` => as described in issue, information is in `hero_stats`

**Comment by SunDwarf** [comment]
I'll take a look in a bit.

**Comment by SunDwarf** [comment]
Okay, I presumably see the bug.

It was incorrectly assumed that the hero-specific stats is always first, when sometimes it's not.  
This has probably been hidden for the better part of 6+ months. Fixing now.

**Comment by Js41637** [comment]
This is the code I use in my API
```
for statsIndex, item in enumerate(stats):
    hero_stats, general_stats, overall_stats, average_stats, featured_stats = {}, {}, {}, {}, []

    hbtitle = item[0].find(".//span[@class='stat-title']").text
    if hbtitle == 'Hero Specific':
        hero_box = item[0]
        startingPos = 1
    else:
        hero_box = None
        startingPos = 0

    # Fetch Hero Specific Stats
    if hero_box is not None:
        for hstat in hero_box.findall(".//tbody/tr"):
            name, value = hstat[0].text.lower().replace(" ", "_").replace("_-_", "_"), hstat[1].text
            amount = utils.parse_int(value, False)
            if 'average' in name.lower():
                average_stats[name.replace("_average", "")] = amount
            else:
                hero_stats[name] = amount

    # Fetch General Hero Stats
    for subbox in item[startingPos:]:
        stats = subbox.findall(".//tbody/tr")
        for stat in stats:
            name, value = stat[0].text.lower().replace(" ", "_").replace("_-_", "_"), stat[1].text
            amount = utils.parse_int(value, False)
            if 'average' in name.lower():
                average_stats[name.replace("_average", "")] = amount
            else:
                general_stats[name] = amount
```

**Comment by SunDwarf** [comment]
Fixed, will go up on hosted version in a few minutes.

**Comment by Js41637** [comment]
👍
