### ISSUE TITLE
heroes.playtime.quickplay is not a Array

### ISSUE THREAD

**Issue by danielsogl** [SunDwarf/OWAPI#158]
## Issue
The object don't return the playtime as an array of objects. Also the *.competitive object

## Links that cause the issue

In JavaScript I do this to create the Array

```
          let heroes: any = [];
          for (let key in this.profile.heroes.playtime.quickplay) {
            heroes.push({ hero: key, playtime: this.profile.heroes.playtime.quickplay[key] });
          }
```

(Surround the links with backticks. Use triple backticks for multiple lines.)

`https://owapi.net/api/v3/u/Dad-12262/heroes`

Hi! Thank you for helping OWAPI by submitting an issue.
Before you submit, please make sure you've done the following:

* [x] Google/Search previous issues to make sure it hasn't been answered before.

* [x] Ask if this is an *OWAPI* issue, or a *Linux* issue, etc.
    * OWAPI requires Python 3.5 or higher installed on a UNIX machine, and it's not really our job to troubleshoot random Linux errors.

Thanks!

**Comment by azah** [comment]
What does that return instead?

**Comment by Js41637** [comment]
I'm not sure what you're asking. The API returns play times as an object of heroes with their playtime.

I assume that code is TS or something but I run
```
let heroes = [];
for (let key in profile.heroes.playtime.quickplay) {
  heroes.push({ hero: key, playtime: profile.heroes.playtime.quickplay[key] });
}
```
where `profile = response.us`
and it gives me
![image](https://cloud.githubusercontent.com/assets/6258213/26086754/fd6d865c-3a2f-11e7-8bc1-9976e8586b8d.png)
Is that not what you want?

**Comment by danielsogl** [comment]
They fixed that issue
