### ISSUE TITLE
Level doesn't count reset

### ISSUE THREAD

**Issue by Crytek** [SunDwarf/OWAPI#16]
Hey, the level output doesn't count the reset that the player made if he past 100 levels.
So the API doesn't show correctly players above level 100.

**Comment by SunDwarf** [comment]
Can you give an example profile?

**Comment by Crytek** [comment]
https://playoverwatch.com/en-us/career/pc/eu/Maru-22750
The "Star" below her level indicates that she went above level 100 and her level reseted to 1.
her level is 140, but the number presented is 40.

**Comment by SunDwarf** [comment]
Not possible to determine via Blizzard's public facing data.

**Comment by Crytek** [comment]
what I did to determine is checking the code for the image of the star and adding 100 to the level number, I did this in c#, hope that will help:
`                string btag = Console.ReadLine();
                btag = btag.Replace("#", "-");
                WebClient example = new WebClient();
                try
                {
                    string code = example.DownloadString("https://playoverwatch.com/en-us/career/pc/eu/"+ btag);

                    // string to handle: <div class="u-vertical-center">10</div>
                    int start = code.IndexOf(@"<div class=""u-vertical-center"">") + 1;
                    int end = code.IndexOf("</div>", start);
                    string result = code.Substring(start, end - start);
                    result = result.Replace(@"div class=""u-vertical-center"">", "");

                    if (code.Contains("0250000000000922_Rank"))
                        result = "1" + result;
                    else
                        if (code.Contains("025000000000093B_Rank"))
                            result = "2" + result;
                        else
                            if (code.Contains("025000000000093C_Rank"))
                                result = "3" + result;
                    int level = Convert.ToInt32(result);
                    Console.WriteLine("Player Level: " + result);
                }
                catch(Exception b)
                {
                    Console.WriteLine(b);
                }`

**Comment by SunDwarf** [comment]
Feel free to open a pull request, then.

I'm not depending on that staying.
