### ISSUE TITLE
/api/v3/u/XXX-12345/achievements returns also heroes

### ISSUE THREAD

**Issue by MTechDE** [SunDwarf/OWAPI#160]
## Issue
When i call the /api/v3/u/XXX-12345/achievements  the API dies not only return the achievements array.
As you can see in the screenshot, the hero array is also submitted with the whole data (not like the stats array).
![image](https://cloud.githubusercontent.com/assets/15234844/25120580/0a6d4ff8-241f-11e7-9f63-90f2e883dae9.png)

In my opinion, the API shouldn't return the heroes and stats array at all.

## Links that cause the issue

`https://owapi.net/api/v3/u/Dad-12262/achievements`

**Comment by SunDwarf** [comment]
I believe I pushed something a few days ago that removed useless keys in all routes, so closing this now.
