### ISSUE TITLE
Run API in background

### ISSUE THREAD

**Issue by svenvonarx** [SunDwarf/OWAPI#161]
## Issue

Hello SunDwarf

At first i wanna say thank you, for sharing this API. With it, it is possible to run a Overwatch competitive toplist for our country.

Is it possible to get a short introduction in the manual for how to run this service in background?

Regards
Sven

**Comment by Neragoth** [comment]
Hi,
Personally I use the Screen Command 
[http://dasunhegoda.com/unix-screen-command/263/](http://dasunhegoda.com/unix-screen-command/263/)

**Comment by azah** [comment]
I'll update the readme. Personally I'd use tmux, but you can also append `&` to the end of a command to make it run in the background.

**Comment by SunDwarf** [comment]
I use a supervisord script to run OWAPI as a service.

```
[program:owapi]
directory=/var/www/owapi.net/
command=/var/www/owapi.net/run.sh
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/owapi/owapi.log
stderr_logfile=/var/log/owapi/owapi.log
user=owapi
stopasgroup=true
```

And run.sh (assuming a virtualenv is under `venv`):
```
#!/usr/bin/env bash
. venv/bin/activate

PATH=venv/bin/:/bin:/usr/bin:/sbin:/usr/sbin

PYTHONPATH=. python -O ./venv/bin/asphalt run -l uvloop config.yml
```
