### ISSUE TITLE
"HTTP Error 403: Forbidden" using the API from Python

### ISSUE THREAD

**Issue by papydeath95** [SunDwarf/OWAPI#162]
## Issue

When i check the API from Google Chrome or Firefox i get the response, but if i try to use it on Python 3.5 i get a "HTTP Error 403: Forbidden"

## Links that cause the issue

`https://owapi.net/api/v3/u/papydeath95-11465/blob`

## Code

```python
import urllib.request, json 
with urllib.request.urlopen("https://owapi.net/api/v3/u/papydeath95-11465/blob") as url:
    data = json.loads(url.read().decode())
    print(data)
```
## Screenshot
![captura de pantalla 88](https://cloud.githubusercontent.com/assets/11861253/25651488/bd6e1268-2fb9-11e7-95fb-1ee4bc45edf3.png)

**Comment by Js41637** [comment]
I think the API doesn't allow requests without a custom user agent?
`DISALLOW_AGENTS = re.compile(r"(?:.*aiohttp/.*|.*python-requests/.*)")`
Don't know if this is the issue.

**Comment by papydeath95** [comment]
I don't know how to use it :'v

**Comment by Js41637** [comment]
Well the code says it returns a `400` but your error says `403` I don't know if that means it's a different issue but. You should try specifying a custom user-agent. The python docs give this example
```
import urllib.request
req = urllib.request.Request(
    url, 
    data=None, 
    headers={
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36'
    }
)

f = urllib.request.urlopen(req)
print(f.read().decode('utf-8'))
```

**Comment by papydeath95** [comment]
![captura de pantalla 92](https://cloud.githubusercontent.com/assets/11861253/25684910/439a321a-303a-11e7-92db-962a0939ea75.png)
It works, but must be fixed because this is not normal (at least in python).

**Comment by Js41637** [comment]
I'm sorry I don't quite understand. SunDwarf has made this API so that you (if your using python at least) you must specify a user-agent to prevent abuse of the service (by bots and such), this isn't an issue in the browser because a user-agent is sent.

**Comment by papydeath95** [comment]
Ah... ok, i think that error was a mistake but was intentionally.
