### ISSUE TITLE
Import Error when running

### ISSUE THREAD

**Issue by miyurusagarage** [SunDwarf/OWAPI#163]
## Issue

I get the error "ImportError: cannot import name 'Type'" when running the asphalt using PYTHONPATH=. asphalt run config.yml. I have set up the dependencies and the virtual environment correctly. The Redis Server also runs fine. I'm using python3.5. Searched for the error, but haven't found any solutions or pointers. Would you happen to know what causes this and why?

**Comment by SunDwarf** [comment]
Could you post the full traceback?

**Comment by miyurusagarage** [comment]
I tried this in AWS linux (based on CentOS and RHEL), but decided to give up because of this error. I tried this on another Ubuntu Server and got it working. Sorry I don't have the traceback anymore. Thanks for the awesome project!
