### ISSUE TITLE
How to know quick play lose point?

### ISSUE THREAD

**Issue by ceomurky** [SunDwarf/OWAPI#165]
Dear develop,

I tried know quick play lose point. So i check your api and find 

> parsing.py 186Line

But this not understand how to know quick play lose point.

So.. i just know how to know quick play lose point.

If you don't mind, please send me your opinion.

Thank you and Regards.

**Comment by Downy** [comment]
I'm not entirely sure what you're asking here.
Could you maybe get someone who speaks English to translate for you?

**Comment by nabijaczleweli** [comment]
This man e-mailed me earlier, so I'll post his original e-mail here in hopes of deciphering. I redirected him to SunDwarf, but he "tired talk to she but not answer anything", then I redirected him here.

>On 27/04/2017 15:58, Jong Min Moon wrote:
> Dear Jędrzej.
>
> I tried make overwatch community site and this site provide user informations.
> But i have one! problem.
>
> That is simple. how to i know overwatch point of  quick play lose?
>
> Official site note provide quick play lose point but your api provide that.
>
> How to know overwatch quick play lose point?
>
>
>
> Thank you and Regards Developer.

**Comment by Js41637** [comment]
Quickplay doesn't track losses.

**Comment by papydeath95** [comment]
Losses = Played - Victories

**Comment by SunDwarf** [comment]
Another satisfied customer.

Next.

**Comment by ceomurky** [comment]
First sorry foolish my english.

But overwatch official site not provide quickplay played score...

**Comment by Js41637** [comment]
Overwatch site does not displays losses or the total games played for Quickplay, OWAPI makes a guess at how many games you have played by dividing your total `Damage Done` by your `Average Damage Done`.
If you've played a lot of games this will give a number that should be pretty close to your total amount of games played and when we have a rough games played number we can calculate the losses.

`games = damage_done / avg_damage_done`
`losses = games - games_won`
