### ISSUE TITLE
-Question/ How to know Quickpaly's played game (Sorry Ask again.!)

### ISSUE THREAD

**Issue by ceomurky** [SunDwarf/OWAPI#166]
First, I apologize for my foolish English skills.

Hello. Developer
I used to check quickplay game played issue. #70
But I don't understand.

How to i know quickplay's played game point?
Overwatch official site not provide Quickpaly's played game point.

Overwatch official site just provide for qucikplay's 

Like this...

GAME
GAMES WON	107
TIME SPENT ON FIRE	02:34:54
OBJECTIVE TIME	01:54:02
TIME PLAYED	25 HOURS

Where is played game (quick play)?

**Comment by Js41637** [comment]
The data you see on the Overwatch site is what available, if you can tell us specifically what you are after than maybe we can help but I don't know what you mean by `played game` Quickplay? Arcade? Competitive?
Are you trying to find the `games_played` value? which doesn't exist  

`game_stats`/`games_played` only exists for competitive
`overall_stats`/`games` exists for both

**Comment by ceomurky** [comment]
That's why I asked the question.
How do you know the score?

Like this

> 
"overall_stats": {"wins": 107, "games": 197, "losses": 90, 

I am tried make a community for overwatch.

But its base is javascript, So .... node.js
 Because python does not know well, I left this question.


So.. how to know OWAPI
Quickplay played game score

like this


> 
"overall_stats": {"wins": 107, "games": 197, "losses": 90,

**Comment by papydeath95** [comment]
It's an API, you send the requests and receive the response.
You will get a json back, parse the json to get the stats.

YOU DON'T NEED TO RUN IT UNTIL YOU ARE DOING BETA TESTING.

**Comment by ceomurky** [comment]
So... how to know api quickplay played game data.... I want know just this.

**Comment by Js41637** [comment]
We can't help those who can't help themselves.

**Comment by SunDwarf** [comment]
The answer has been provided above (I think?). Regardless, I don't understand your question so I can't help further.
