### ISSUE TITLE
Achievements not added

### ISSUE THREAD

**Issue by Kezyma** [SunDwarf/OWAPI#168]
It's not really an issue, but a requested update, currently the achievements for the most recent event aren't part of the API, I was wondering if there were plans to add them any time soon?

**Comment by Js41637** [comment]
New achievements haven't been added to the website yet, until they are added to the website, it won't be possible to return data for them. Sorry.

**Comment by Kezyma** [comment]
Ahh, that makes sense, I'll keep an eye out for them on their site! Thanks

**Comment by Js41637** [comment]
Status update: They're still not added.

**Comment by Js41637** [comment]
Uprising achievements have been added to the website now.

**Comment by SunDwarf** [comment]
Does the code automatically fetch them or do I need to write code to detect them?

**Comment by Js41637** [comment]
I've got no clue, I figured the code just mapped them automatically, I haven't actually tested.

**Comment by SunDwarf** [comment]
Good enough for me!

**Comment by Js41637** [comment]
Seems to be working for me!
