### ISSUE TITLE
Stats update only when you leave the game?

### ISSUE THREAD

**Issue by SenpaiRemling** [SunDwarf/OWAPI#171]
Is it possible that the stats from the api are only updated once you left the game completly? while im in the game, even when im not playing, the api doesnt update? is that normal?

**Comment by Avaren** [comment]
Blizzard limitation, same for all their games

**Comment by SunDwarf** [comment]
Yes, stats are only updated when the game is exited. This is a limitation from Blizzard; who do not update them in real time.

**Comment by Js41637** [comment]
You forgot the `fucking blizzard` tag

**Comment by azah** [comment]
Na this is entirely reasonable on Blizzard's part. That tag is for them arbitrarily not displaying certain stats, etc
