### ISSUE TITLE
Last played datetime & with whom

### ISSUE THREAD

**Issue by rafapaulin** [SunDwarf/OWAPI#172]
Hi there =)

Is there, by any chance, a way to retrieve the last time a given players logged on the game, and a list of that player's X last matches (who that given player has played with/against)?

I am willling to contribute with your API if you need any help coding that kind of feature (considering that retrieving that data is somehow currently possible).

Thanks!
Best regards

**Comment by Js41637** [comment]
This data is not available. OWAPI gets it's data from users public profile pages. Only the data you see on the page is what can be returned.

**Comment by rafapaulin** [comment]
Tyvm =)
