### ISSUE TITLE
venv

### ISSUE THREAD

**Issue by rafapaulin** [SunDwarf/OWAPI#174]
## Issue
Hello. I am new on python (and quite new on programming), so, I am sorry about lame questions.
I am getting the following error when trying to run `python3.5 -m venv ./venv` on API root dir.

> Error: [Errno 71] Protocol error: 'lib' -> '/home/vagrant/lab/OWAPI/venv/lib64'

Any idea what could I do?

Apart of that, My application is a php-based one. Is there a way to access the data returned from your api directly?

Thanks

**Comment by azah** [comment]
https://stackoverflow.com/questions/24640819/protocol-error-setting-up-virtualenvironment-through-vagrant-on-ubuntu

**Comment by rafapaulin** [comment]
Thanks!

Can I/Should I use your endpoints in prod env (as I am doind with the sc2 oficcial blizz api), or must I instantiate it?

Thanks once more

**Comment by azah** [comment]
You're better off instantiating your own for production.

Otherwise talk to @SunDwarf . 
https://www.patreon.com/sundwarf
