### ISSUE TITLE
Stats for competitive season 5 is not reset.

### ISSUE THREAD

**Issue by nocodeinput** [SunDwarf/OWAPI#175]
## Issue
Stats was not reset to 0 in the new season. Example profile below.

## Links that cause the issue
`https://owapi.net/api/v3/u/Half-2673/stats`

**Comment by Jadeskycore** [comment]
I think that behavior is expected. It will return previous season info until you calibrate in new season.

**Comment by Js41637** [comment]
We only return what is on your public profile, you public profile returns your old season stats until you have new ones.

**Comment by SunDwarf** [comment]
Yes, this is intended behaviour. My profile even contains my Season 1 competitive rank still.

**Comment by nocodeinput** [comment]
I see... That explains it.. Guess i have to figure out a clever solution on my end. Thanks for the replies :-)
