### ISSUE TITLE
Wrong number of games

### ISSUE THREAD

**Issue by MaxdeoxiS** [SunDwarf/OWAPI#178]
## Issue

Since yesterday OW update ("Averages are now calculated in 10-minute slices, rather than by the number of games played", https://us.battle.net/forums/en/overwatch/topic/20756815859), the number of games calculated here https://github.com/SunDwarf/OWAPI/blob/master/owapi/v3/parsing.py#L240 is wrong

**Comment by SunDwarf** [comment]
Hmm. I can't immediately see any stats that can now be used to calculate the total games played.

**Comment by SunDwarf** [comment]
Of course the chance of this being true for the website is close to 0% so I'm not too sure the current numbers are that inaccurate, however.

**Comment by MaxdeoxiS** [comment]
They are. Example for my profile : https://owapi.net/api/v3/u/MaxdeoxiS-2292/stats , in quickplay it says I've played 897141 games lol.
Moreover, there seems to be something weird on the website : in the  "Miscellaneous" stats section, there are a few "overwatch.guid.0xHEXA_VALUE" stats now. Surely it'll be fixed by blizzard anytime soon I hope

**Comment by WouterLindeboom** [comment]
> Surely it'll be fixed by blizzard anytime soon
My sweet summer child

**Comment by SunDwarf** [comment]
They make one change and it's this one. Alright. Fucking blizzard.

**Comment by MaxdeoxiS** [comment]
Actually, their "damage done - average" (on the website) stat is weird. It's extremely low (between 10 and 20), that's why we're having huge number of game when dividing total damage done by this weird new (bugged?) extremely low stat.

Using other stats produce something more realistic, I got nearly the same result with "solo kills," "eliminations" and "deaths"

**Comment by Js41637** [comment]
The site is not updated to support the changes the game recently made. I don't have high hopes that the site will be updated anytime soon.

**Comment by SunDwarf** [comment]
This should be "fixed". It's not accurate still, but it's good enough for now.
