### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by jkroepke** [SunDwarf/OWAPI#179]
## Issue

Add support though proxy, if server is behind a firewall

## Links that cause the issue

N/A

Hi! Thank you for helping OWAPI by submitting an issue.
Before you submit, please make sure you've done the following:

* [X] Google/Search previous issues to make sure it hasn't been answered before.

* [ ] Ask if this is an *OWAPI* issue, or a *Linux* issue, etc.
    * OWAPI requires Python 3.5 or higher installed on a UNIX machine, and it's not really our job to troubleshoot random Linux errors.

http://docs.python-requests.org/en/master/user/advanced/#proxies
I have defined the proxy variable and I verify it with `cat /proc/PID/envrion`

No idea, if this a python limitation (see link above), because you are using the get method agist a already existing session object (ctx.session.get).

Thanks!

**Comment by SunDwarf** [comment]
aiohttp requires a special parameter passed to use proxy from an environment variable. Should be usable now.
