### ISSUE TITLE
403 Fobidden on owapi.net

### ISSUE THREAD

**Issue by ModdyLP** [SunDwarf/OWAPI#183]
## Issue
Everytime I try to query your Restapi, i get a 403 Forbidden error.
I use Java 1.8 and a BufferedInputStream to connect to your RestAPI.

I use the public owapi on owapi.net.

With my Browser all works fine.

## Links that cause the issue

(Surround the links with backticks. Use triple backticks for multiple lines.)

`https://owapi.net/api/v3/u/ModdyPlays-2418/stats?format=json_pretty&platform=xbl`

`https://owapi.net/api/v3/u/ModdyPlays-2418/stats?format=json_pretty`

`https://owapi.net/api/v3/u/ModdyPlays-2418/stats`

Hi! Thank you for helping OWAPI by submitting an issue.
Before you submit, please make sure you've done the following:

* [x] Google/Search previous issues to make sure it hasn't been answered before.

* [x] Ask if this is an *OWAPI* issue, or a *Linux* issue, etc.
    * OWAPI requires Python 3.5 or higher installed on a UNIX machine, and it's not really our job to troubleshoot random Linux errors.

Thanks!

**Comment by SunDwarf** [comment]
I can't see any 403s in my access log - you could be blocked by Cloudflare for some reason. What's the actual response from the server?

**Comment by ModdyLP** [comment]
I get this exception in my java program: ```17-07-4:11-01:24[MoMuOSB][DEBUG]https://owapi.net/api/v3/u/ModdyPlays-2418/stats?format=json_pretty&platform=xbl
java.io.IOException: Server returned HTTP response code: 403 for URL: https://owapi.net/api/v3/u/ModdyPlays-2418/stats?format=json_pretty&platform=xbl
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at java.net.URL.openStream(URL.java:1045)
        at storage.WebClient.fetchUrl(WebClient.java:36)
        at storage.RestRequest.fetchResult(RestRequest.java:75)
        at storage.RestRequest.fetchJson(RestRequest.java:86)
        at modules.Gamestats.getGameStats(Gamestats.java:34)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at events.EventListener.initiateCommand(EventListener.java:116)
        at events.EventListener.lambda$onMessageReceivedEvent$0(EventListener.java:74)
        at java.lang.Thread.run(Thread.java:745)
17-07-4:11-01:24[MoMuOSB][DEBUG]{"error":"null"}```
I dont think that you can do something with that. I get no website displayed because the error appears before recieving content.

**Comment by SunDwarf** [comment]
Sorry, I can't help without seeing the full response.

**Comment by ModdyLP** [comment]
Thats all can get from java side. The error comes before i get a useall response. But I am trying some things. I think you defined a user-agent filter and I dont have a user-agent set in my program.

**Comment by ModdyLP** [comment]
The complete content of response:
```
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Access denied | owapi.net used Cloudflare to restrict access</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>
<!--[if lte IE 9]><script type="text/javascript" src="/cdn-cgi/scripts/jquery.min.js"></script><![endif]-->
<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script><!--<![endif]-->
<script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>

</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1>
          <span class="cf-error-type" data-translate="error">Error</span>
          <span class="cf-error-code">1010</span>
          <small class="heading-ray-id">Ray ID: 37914d14c9cf723b &bull; 2017-07-04 10:11:33 UTC</small>
        </h1>
        <h2 class="cf-subheadline" data-translate="error_desc">Access denied</h2>
      </div><!-- /.header -->

      <section></section><!-- spacer -->

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="what_happened">What happened?</h2>
            <p>The owner of this website (owapi.net) has banned your access based on your browser's signature (37914d14c9cf723b-ua21).</p>
          </div>


        </div>
      </div><!-- /.section -->

      <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">Cloudflare Ray ID: <strong>37914d14c9cf723b</strong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span data-translate="your_ip">Your IP</span>: 212.75.61.220</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span data-translate="performance_security_by">Performance &amp; security by</span> <a data-orig-proto="https" da
5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>

  </p>
</div><!-- /.error-footer -->


    </div><!-- /#cf-error-details -->
  </div><!-- /#cf-wrapper -->

  <script type="text/javascript">
  window._cf_translation = {};


</script>

</body>
</html>
```

**Comment by ModdyLP** [comment]
Okay i have found a solution, I have to define the User-Agent to Mozilla Firefox.
