### ISSUE TITLE
Finding battletags online

### ISSUE THREAD

**Issue by dfreelan** [SunDwarf/OWAPI#185]
I have this set up and it's working great!

I'd really like to get a load of statistics about players in competitive. How might one go about getting a list of publicly available battletags to get statistical information on?

I figure somebody around here might have found that out already! feel free to email (my email is in my profile)  me if this is not the appropriate forum to ask.

**Comment by azah** [comment]
You could scrape through overbuff or masteroverwatch's web pages. I dunno otherwise.
