### ISSUE TITLE
pip install -r rquirements.txt fails in some python command

### ISSUE THREAD

**Issue by marqueles** [SunDwarf/OWAPI#189]
## Issue

Hi!, When executing the command pip install -r requirements.txt I get:

Collecting Kyoukai<=2.3.0,>=2.1.4 (from -r requirements.txt (line 1))
  Using cached Kyoukai-2.2.1-py3-none-any.whl
Collecting aioredis<=1.0.0,>=0.3.0 (from -r requirements.txt (line 2))
  Using cached aioredis-0.3.3-py3-none-any.whl
Collecting aiohttp<=2.3.0,>=2.2.0 (from -r requirements.txt (line 3))
  Using cached aiohttp-2.2.3-cp35-cp35m-manylinux1_x86_64.whl
Collecting asphalt==4.0.0 (from -r requirements.txt (line 4))
  Using cached asphalt-4.0.0-py3-none-any.whl
Collecting asphalt-redis==2.0.1 (from -r requirements.txt (line 5))
  Using cached asphalt_redis-2.0.1-py3-none-any.whl
Collecting asyncio-extras<=1.4.0,>=1.3.0 (from -r requirements.txt (line 6))
  Using cached asyncio_extras-1.3.0-py3-none-any.whl
Collecting html5_parser==0.3.3 (from -r requirements.txt (line 8))
  Using cached html5-parser-0.3.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-62qd_gwh/html5-parser/setup.py", line 79, in <module>
        include_dirs=include_dirs(),
      File "/tmp/pip-build-62qd_gwh/html5-parser/build.py", line 89, in include_dirs
        return [x[2:] for x in pkg_config('libxml-2.0', '--cflags-only-I')]
      File "/tmp/pip-build-62qd_gwh/html5-parser/build.py", line 75, in pkg_config
        val = subprocess.check_output([PKGCONFIG, pkg] + list(args)).decode('utf-8')
      File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.5/subprocess.py", line 383, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'pkg-config'

---------------------------------------------------------------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-e367f_02/html5-parser/

This causes the next command ( PYTHONPATH=. asphalt run config.yml) to output:
asphalt: command not found.

Thanks for the help!

Hi! Thank you for helping OWAPI by submitting an issue.
Before you submit, please make sure you've done the following:

* [x] Google/Search previous issues to make sure it hasn't been answered before.

* [ ] Ask if this is an *OWAPI* issue, or a *Linux* issue, etc.
    * OWAPI requires Python 3.5 or higher installed on a UNIX machine, and it's not really our job to troubleshoot random Linux errors.

Thanks!

**Comment by SunDwarf** [comment]
Odd, `pkg-config` should be installed anyway.

Try `pip install -U pkg-config` before installing requirements.

**Comment by miyurusagarage** [comment]
I encountered this issue and fixed it by reinstalling pkg-config using "sudo apt install pkg-config" then updating the pip version, and reactivating the virtual environment.
