### ISSUE TITLE
Cannot check what region is valid

### ISSUE THREAD

**Issue by TheOnlyArtz** [SunDwarf/OWAPI#190]
## Issue

I'm using nodejs and javascript cannot recognize what is the JSON's variable
And what's a custom variable so it is impossible for me to filter out what regions are valid
If you can get all the regions into an array it will be so helpful because simply looping through and looks what null will be a great solution

(And yes I know I can just check for each one and act for that region but I don't want my code to be 300 lines
Although with array I can do that in 50)

## Links that cause the issue

(Surround the links with backticks. Use triple backticks for multiple lines.)

`https://owapi.net/api/v3/u/Dad-12262/blob`

Hi! Thank you for helping OWAPI by submitting an issue.
Before you submit, please make sure you've done the following:

* [ ] Google/Search previous issues to make sure it hasn't been answered before.

* [ ] Ask if this is an *OWAPI* issue, or a *Linux* issue, etc.
    * OWAPI requires Python 3.5 or higher installed on a UNIX machine, and it's not really our job to troubleshoot random Linux errors.

Thanks!

**Comment by Js41637** [comment]
i'm confused what the issue is? You can't have you're code pick 3 regions out of a json object?

**Comment by TheOnlyArtz** [comment]
I can't make my application loop through all the loops and know whats valid... then make it pick up the stats from the valid region

Nodejs

**Comment by Js41637** [comment]
I don't know what type of data you're trying to get but there are definitely ways to get the data you need.

Will return array of regions that have data in the object
`["us", "eu", "kr", "any"].filter(region => blob[region])`

Go through every region with data
```
["us", "eu", "kr", "any"].forEach(region => {
  const data = blob[region]
  if (!data) return
  console.log(region, data)
})
```

**Comment by TheOnlyArtz** [comment]
First time I didn't think about loops like that... Come on Artz get more creative 🗡 

```css
Thank you !
```
