### ISSUE TITLE
Average stats missing?

### ISSUE THREAD

**Issue by DanielMarquard** [SunDwarf/OWAPI#192]
Are average stats broken? On my local API, I get this message:

```
{"msg":"please report this!","error":500,"exc":"KeyError(\'eliminations_avg\',)"}
```

On the [hosted API](https://owapi.net/api/v3/u/D3%C7%B6-1818/blob?platform=pc), I see this for average stats:

```
"average_stats": {}
```

**Comment by SunDwarf** [comment]
Average stats appear to have gone missing from the website again.

The local API error is due to being on an outdated version.

**Comment by DanielMarquard** [comment]
OK, thank you. I will update our API locally. When 100K users complain at once, you know Overwatch broke something. 😆 

So average stats have gone missing in the past? Do they remove them and add them back later or something? Great work on this API, by the way.

**Comment by SunDwarf** [comment]
Blizzard seems to break the website I scrape from randomly, unfortunately. I saw the first signs of this last night, but I hoped it was isolated cases.

**Comment by azah** [comment]
At this point I think Blizzard just hates us.
No actual API, just a website that they change randomly...

**Comment by kitsun8** [comment]
I made a bug report about this, but obviously Blizzard is in no rush to fix their shit. The Average DMG/10minutes stat is hilariously broken as well on the site.

https://us.battle.net/forums/en/overwatch/topic/20758585728#post-1

**Comment by Js41637** [comment]
you must be new here

**Comment by kitsun8** [comment]
Not new, I've just observed until now. I am very well avare of Blizzard'd incapability to take user voices into account :) :+1: 

As much as I'd like to work there one day, they make themselves hard to like amongst developers outside their company. No API, no proper Observer tooling (See HLTV or Dota) etc etc etc.

**Comment by Js41637** [comment]
Yeah was just messin' around. They obviously either have a separate web team or just do the bare minimum as they don't have anyone to work on it. There is a listing on Blizzards Job page for a Web Developer for Overwatch so, maybe one day it won't be shit.

**Comment by kitsun8** [comment]
True. I'm willing to bet.. okay I'm not, but they should have an API in place when Overwatch League starts.

Just a though, meanwhile we could get some of the averages by getting the total amount of games, and divide total eliminations, deaths, healing, medals with that. Not saying it needs to be implemented to OWAPI, because the data is there in current API, just need to access it via different means.

**Comment by SunDwarf** [comment]
I actually question if anyone's looked at the page since it was updated. The averages are still there - I just don't parse them correctly. 

And they're ten minute rolling averages instead. >.>

**Comment by SunDwarf** [comment]
This seems like a permanent feature now. I now parse rolling average stats instead. Sorry peoples.
