### ISSUE TITLE
Get all users' data

### ISSUE THREAD

**Issue by nextonstudio** [SunDwarf/OWAPI#197]
## Get all users'  data
OWAPI of now only support the one user data at once. I know OWAPI's function is based on Blizzard Search System. It's difficult to do it but can you tell me how can I get all users' data?

**Comment by Js41637** [comment]
What do you mean by all users data?

**Comment by azah** [comment]
In your code, write it to loop over an array of the users you want, or something.

```rb
array_of_users = ["x", "y", "z"]

array_of_users.each do |user|
  request(... + user)
  sleep(30)
end
```

is one example in ruby. Please

**Comment by Lord-Protector** [comment]
@azah why use sleep? `request` is async operation? I just resolve 3-5 requests parallely and then wait then they will complete, then again.

**Comment by Js41637** [comment]
maybe as to not spam the api with requests?

**Comment by Lord-Protector** [comment]
I use my own intance :)

**Comment by Js41637** [comment]
Oh cool. Point still stands tho

**Comment by SunDwarf** [comment]
Just loop over a list of battletags you've got.

**Comment by nextonstudio** [comment]
OK. Thanks to answer me!
