### ISSUE TITLE
Support for 'All Modes' and previous Competitive Seasons?

### ISSUE THREAD

**Issue by EthanChrisp** [SunDwarf/OWAPI#198]
Is it a possibility to support the 'All Modes' statistics that can be found in game? This tab returns cumulative values across all Competitive Seasons, Quickplay, against AI, and so on (minus Arcade). Would be great if it was possible to be supported in this API.

Next. is it possible to pull data from previous Competitive Seasons, rather than the current?

**Comment by azah** [comment]
The only data we can get is from the playoverwatch.com page. 
https://playoverwatch.com/en-us/career/pc/us/Dad-12262

So we can't get previous seasons nor all modes.
With OWAPI you can get your quickplay and competitive stats, and sum them up.
