### ISSUE TITLE
Profile not returing correct data

### ISSUE THREAD

**Issue by nocodeinput** [SunDwarf/OWAPI#199]
## Issue

https://owapi.net/api/v3/u/Zappy-21908/stats returns 0 games played for eu - competitive. Comparing it to overbuff or Blizzard's site https://playoverwatch.com/en-us/career/pc/eu/Zappy-21908 you can see the player has 24 games played

## Links that cause the issue

`https://owapi.net/api/v3/u/Zappy-21908/stats`

**Comment by azah** [comment]
It says 24 for me

**Comment by nocodeinput** [comment]
Sorry, the overall_stats

**Comment by ndyarborough** [comment]
How do you need to format the battletag? I have tried just entering directly into this route:

**Comment by ndyarborough** [comment]
Trouble formatting battletag for - GET /api/v3/u/:battletag/stats, cannot find info on my own gamertag.

**Comment by ndyarborough** [comment]
Any suggestions?

**Comment by nocodeinput** [comment]
remove the : in front of battletag and remember its case sensitive. If it does not work, paste the URL youre trying to use.

**Comment by SunDwarf** [comment]
So every time I see an issue here, I usually type up something like "Gonna investigate this, give me a bit". Then I forget to send, and when the issue pops up in my email, I do the same process until like 3 months later I finally figure out how to reply to an issue.

So, I'm actually gonna look into this now.

**Comment by ndyarborough** [comment]
I was not using battletag properly, attempting to use my xbox live gamertag in the request parameter for /:battletag. I did not have a battle.net account tied to my overwatch account on Xbox Live. I had to create a battle.net account, link my overwatch profile to the battle.net account, and use the battletag I was given there.
