### ISSUE TITLE
Losses and total games counts are always 0 for quick play statistics.

### ISSUE THREAD

**Issue by N3-M3-S1S** [SunDwarf/OWAPI#200]
## Issue
When i try to get my quick play statistics only wins count is valid, losses and total games counts are always 0. Everything is fine with competitive stats though. 

Here is an example of the response for my quick play stats:
```quickplay: {
competitive: false,
overall_stats: {
avatar: "https://d1u1mce87gyfbn.cloudfront.net/game/unlocks/0x02500000000008C1.png",
comprank: 2652,
losses: 0,
win_rate: 0,
prestige: 2,
rank_image: "https://d1u1mce87gyfbn.cloudfront.net/game/playerlevelrewards/0x025000000000093F_Border.png",
level: 57,
wins: 745,
games: 0,
tier: "platinum"
}
```

**Comment by SunDwarf** [comment]
Blizzard just doesn't provide the data for this. We used to calculate an estimate, but the method can't be used anymore.

**Comment by SunDwarf** [comment]
See also: #70, #83
