### ISSUE TITLE
The new update had destroys my comparision site

### ISSUE THREAD

**Issue by Domekologe** [SunDwarf/OWAPI#202]
## Issue

With the new update you have send all general stats codes to the average stats, so all my datas are lost on the site. I've change your script and I've turned it back to general_stats (Herostats).
Can you please change it back in your next update?

Its really hard for me because I've saved all files from the other seasons to get a complete overview.

Thanks

**Comment by SunDwarf** [comment]
No. The fact that the averages were even in general stats was a bug.

**Comment by Domekologe** [comment]
But now all stats are in the average_stats and the general_stats are now empty :/
So I think I must write an extra line for all other seasons

**Comment by SunDwarf** [comment]
That's a separate bug, and it would be better to report it without a sensationalist title next time.
