### ISSUE TITLE
Cannot run the server with default requirements

### ISSUE THREAD

**Issue by CRamsan** [SunDwarf/OWAPI#207]
## Issue

Trying to run the server with the provided instructions may not work if aioredis version 1.X is installed. The error is "ImportError: cannot import name 'create_reconnecting_redis'". Aioredis dropped support for create_reconnecting_redis in version 1 so I modified the requirements file to install aioredis<1 and that seem to work.

In my case I tested this on Arch linux, maybe on other distros such as Ubuntu, aioredis versions 1 is not yet available. 

diff --git a/requirements.txt b/requirements.txt
index 8d29872..e245521 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,5 +1,5 @@
 Kyoukai>=2.1.4,<=2.3.0
-aioredis>=0.3.0,<=1.0.0
+aioredis>=0.3.0,<1.0.0
 aiohttp>=2.2.0,<=2.2.5

This is how I solved it for me.

**Comment by SunDwarf** [comment]
Changed, thanks.
