### ISSUE TITLE
overall_stats not being returned (competitive)

### ISSUE THREAD

**Issue by mdotk** [SunDwarf/OWAPI#210]
## Issue

Win Rate, Games and a number of other stats under "overall_stats" are not being recorded for competitive

## Links that cause the issue

`https://owapi.net/api/v3/u/SharP-21704/stats?platform=pc` (example of error)
`https://owapi.net/api/v3/u/carpe-31193/stats?platform=pc` (working correctly)

SharP is active however:
`https://www.overbuff.com/players/pc/SharP-21704`
`https://playoverwatch.com/en-us/career/pc/SharP-21704`

The stats under locale > stats > competitive > overall_stats are not being returned. This seems to affect about 90% of the profiles I attempt to look up. I am not sure why it affects some and not others.

**Comment by Js41637** [comment]
Probably related to #209 as the position of the stats seems to have changed.

**Comment by mdotk** [comment]
Woops, sorry I missed that.
