### ISSUE TITLE
Can't Query for a User ID That Does Not Have #s In IT

### ISSUE THREAD

**Issue by extralogical** [SunDwarf/OWAPI#214]
## Issue

I can't query for user IDs that don't have numbers.

## Links that cause the issue
`https://owapi.net/api/v3/u/STARdot_/blob`

But this player's profile can be accessed via browser here:

`https://playoverwatch.com/en-us/career/psn/STARdot_`

Hi! Thank you for helping OWAPI by submitting an issue.
Before you submit, please make sure you've done the following:

* [X] Google/Search previous issues to make sure it hasn't been answered before.

* [X] Ask if this is an *OWAPI* issue, or a *Linux* issue, etc.
    * OWAPI requires Python 3.5 or higher installed on a UNIX machine, and it's not really our job to troubleshoot random Linux errors.

Thanks!

**Comment by extralogical** [comment]
I think I have to explicitly query PSN.

**Comment by Js41637** [comment]
Yeah I don't think this is a bug, the api defaults to PC. If you want to check someone on a different platform you need to explicitly tell it.

`https://owapi.net/api/v3/u/STARdot_/blob?platform=psn` works

**Comment by extralogical** [comment]
Yeah - I was just going to post the same working URL.  Thanks I figured it out.  Closing.
