### ISSUE TITLE
Able to distinguish prestige [over level 100] ?

### ISSUE THREAD

**Issue by grepString** [SunDwarf/OWAPI#22]
Thanks for all the work so far, everything works great. Do you think it'd be possible to get a prestige level? Thoughts?

Thanks!

**Comment by Js41637** [comment]
The only way to do this would be to identify the css background image used for each of the stars

**Comment by azah** [comment]
Player level CSS:
```css
.player-level {
    background-image: url(https://blzgdapipro-a.akamaihd.net/game/playerlevelrewards/{PICTURE_NAME})
}
```

Non Prestige:
```
0x0250000000000921_Border.png
```

Prestige 1
```
0x025000000000094C_Border.png
```

Prestige 2
```
0x0250000000000937_Rank.png
```

Reference URLs:
---
Non-Prestige: https://playoverwatch.com/en-us/career/pc/us/Dad-12262
P1: https://playoverwatch.com/en-us/career/pc/us/z1Ad-1583
P2: https://playoverwatch.com/en-us/career/pc/us/soulive-1406

**Comment by Js41637** [comment]
The rank is stored on its own class `.player-rank` unfortunately the rank image correlates to the type of border image and the borders change as you level up (every 10 levels?)

**Comment by grepString** [comment]
@azah Hey, thanks for that. Very helpful.

**Comment by SunDwarf** [comment]
This was easier than I thought.

`prestige` key as been added to `overall_stats`, and represents their number.

**Comment by grepString** [comment]
Actually ran into an issue retrieving prestige level from 2 people. (haven't tested others)

**Player 1** _Xuja#11513_
https://owapi.net/api/v2/u/Xuja-11513/stats/general
https://playoverwatch.com/en-us/career/pc/us/Xuja-11513

**Player 2** _Lexonic#1601_
https://owapi.net/api/v2/u/Lexonic-1601/stats/general
https://playoverwatch.com/en-us/career/pc/us/Lexonic-1601

Each player has 1 prestige level but the API is returning null for each. Any ideas?

**Comment by Js41637** [comment]
As I mentioned the star image is linked to the border image (same ids) and
you get a new border every 10 levels, so in order to determine the rank you
will need all 10 ids that correlate to the rank for each border

**Comment by azah** [comment]
That's too much work. 

Other stats sites like Overbuff & MO have the level in plaintext.
