### ISSUE TITLE
Question about User-Agent preferences

### ISSUE THREAD

**Issue by JoshCode** [SunDwarf/OWAPI#220]
## Issue
Hi SunDwarf and contributors,

This API is awesome, I've just begun using it for some Discord interactions with Overwatch. I saw that to make API requests I need to customize my User-Agent header, but I couldn't find any preferred format for it. I've set it to `<my app URL>:<version ID>` currently. Is that fine, or do you have a preferred format for it?

## Links that cause the issue

Not applicable

---

Hi! Thank you for helping OWAPI by submitting an issue.
Before you submit, please make sure you've done the following:

* [x] Google/Search previous issues to make sure it hasn't been answered before.

* [x] Ask if this is an *OWAPI* issue, or a *Linux* issue, etc.
    * OWAPI requires Python 3.5 or higher installed on a UNIX machine, and it's not really our job to troubleshoot random Linux errors.

Thanks!

**Comment by SunDwarf** [comment]
There's no specific format for the User-Agent, just something identifiable and unique to you, so that I can roughly track usages of the API.
