### ISSUE TITLE
Problem retrieving prestige level

### ISSUE THREAD

**Issue by grepString** [SunDwarf/OWAPI#25]
@SunDwarf 

Ran into an issue retrieving prestige level from 2 people. (haven't tested others)

**Player 1** _Xuja#11513_
https://owapi.net/api/v2/u/Xuja-11513/stats/general
https://playoverwatch.com/en-us/career/pc/us/Xuja-11513

**Player 2** _Lexonic#1601_
https://owapi.net/api/v2/u/Lexonic-1601/stats/general
https://playoverwatch.com/en-us/career/pc/us/Lexonic-1601

Each player has 1 prestige level but the API is returning null for each. Any ideas?

Thanks!

**Comment by SunDwarf** [comment]
Their rank (`028`) appears to be new.

I'll fix/add this as another one for `1` Soon™.

**Comment by SunDwarf** [comment]
Should be fixed.

**Comment by grepString** [comment]
I do believe it changed...again. What the hell is even happening with Blizzard.

`https://blzgdapipro-a.akamaihd.net/game/playerlevelrewards/0x0250000000000924_Rank.png`

**Comment by Js41637** [comment]
>As I mentioned the star image is linked to the border image (same ids) and
you get a new border every 10 levels, so in order to determine the rank you
will need all 10 ids that correlate to the rank for each border

**Comment by SunDwarf** [comment]
Re-opened as there's lots of borders to get.

**Comment by Js41637** [comment]
I wrote a script to fetch the top ids from Master Overwatch (sorted by level) but it only returns like the top 500 users which are all high levels, no way to get lower levels from MO

**Comment by Js41637** [comment]
Using some serious sourcery and scripting, I'm fairly certain these are accurate and should be all ranks from 0 to 5, rank 6 uses a silver portrait
```
"0x0250000000000918": 0
"0x0250000000000919": 0
"0x025000000000091A": 0
"0x025000000000091B": 0
"0x025000000000091C": 0
"0x025000000000091D": 0
"0x025000000000091E": 0
"0x025000000000091F": 0
"0x0250000000000920": 0
"0x0250000000000921": 0
"0x0250000000000922": 1
"0x0250000000000924": 1
"0x0250000000000925": 1
"0x0250000000000926": 1
"0x025000000000094C": 1
"0x0250000000000927": 1
"0x0250000000000928": 1
"0x0250000000000929": 1
"0x025000000000092B": 1
"0x0250000000000950": 1
"0x025000000000092A": 2
"0x025000000000092C": 2
"0x0250000000000937": 2
"0x025000000000093B": 2
"0x0250000000000933": 2
"0x0250000000000923": 2
"0x0250000000000944": 2
"0x0250000000000948": 2
"0x025000000000093F": 2
"0x0250000000000951": 2
"0x025000000000092D": 3
"0x0250000000000930": 3
"0x0250000000000934": 3
"0x0250000000000938": 3
"0x0250000000000940": 3
"0x0250000000000949": 3
"0x0250000000000952": 3
"0x025000000000094D": 3
"0x0250000000000945": 3
"0x025000000000093C": 3
"0x025000000000092E": 4
"0x0250000000000931": 4
"0x0250000000000935": 4
"0x025000000000093D": 4
"0x0250000000000946": 4
"0x025000000000094A": 4
"0x0250000000000953": 4
"0x025000000000094E": 4
"0x0250000000000939": 4
"0x0250000000000941": 4
"0x025000000000092F": 5
"0x0250000000000932": 5
"0x025000000000093E": 5
"0x0250000000000936": 5
"0x025000000000093A": 5
"0x0250000000000942": 5
"0x0250000000000947": 5
"0x025000000000094F": 5
"0x025000000000094B": 5
"0x0250000000000954": 5
```

**Comment by SunDwarf** [comment]
#29 should fix this, hopefully, thanks to @Js41637
