### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by psegovias** [SunDwarf/OWAPI#27]
Hi @SunDwarf how i can install this? there's a guide to do it?

Regards!

**Comment by Downy** [comment]
https://github.com/SunDwarf/OWAPI/issues/1
Read these comments, there's an explanation on how to install this.

**Comment by azah** [comment]
It may be good to create an Install.md. @SunDwarf 

You need Python 3 and an instance of Redis running on the default port (6397?).

What are you running this on? I can write a guide for Ubuntu 14.04 (what I use to run my instance of it).

**Comment by psegovias** [comment]
@azah im running ubuntu 14.04 too.

**Comment by azah** [comment]
`apt-get python3` wont work because it's 3.4.

You can build your own 3.5 in /opt/ or wherever, or you can use [Felix Krull's PPAs](https://launchpad.net/%7Efkrull/+archive/ubuntu/deadsnakes/+index?batch=75&memo=75&start=75).

```bash
sudo add-apt-repository ppa:fkrull/deadsnakes
sudo apt-get update
sudo apt-get install python3.5
sudo apt-get install redis-server
```

```
python3.5 -m pip install -r requirements.txt
PYTHONPATH=. asphalt run -l uvloop config.yml
```

and just run that with screen/tmux.
