### ISSUE TITLE
Player profiles sometimes return 404 and can work fine again some minutes later

### ISSUE THREAD

**Issue by drywolf** [SunDwarf/OWAPI#33]
Hi,

I am using the API for a [TeamSpeak 3 plugin](https://github.com/drywolf/ts3-overwatch-stats-plugin) of mine to show player statistics in the client.

While testing my code I found that sometimes a player profile can suddenly return a 404 and be back to normal again just some minutes later.

For example just some minutes ago this profile: https://owapi.net/api/v2/u/Sigi-2686/stats/general returned a standard 404 response of the API:

    {"region": null, "msg": "profile not found", "_request": {"route": "/api/v2/u/Sigi-2686/stats/general", "api_ver": 2}, "error": 404}

Now (some minutes have passed) the same profile is back to normal and returns the JSON data as expected.
I don't think that it is related only to certain profiles but it can happen to any profile occasionally.
So far it has happend very occasionally to some random profiles that I was testing during the day.

**Comment by azah** [comment]
That happens on Blizzard's site sometimes I've noticed.

**Comment by Js41637** [comment]
Yeah there isn't much that can be done, it's because the site didn't load correctly, not sure why, could be a rate limit thing or maybe it timeouts.

**Comment by SunDwarf** [comment]
This is two things; Blizzard being bad and the aggressive caching I perform.

All data is cached for 300 seconds after retrieval to prevent every request being incredibly slow. This, as you've noticed, has the side effect of caching bad data when blizzard decides to be silly and not return the right data.

I'm going to keep this open for a bit, until I implement a way to either not cache data when it 404s (which isn't needed as the 404 page is much faster to load than the player page) or do it for a short time.

**Comment by SunDwarf** [comment]
Basically, if you request a profile; there's no guarantee it will be there. However, it's recommended to retry the request after 5 seconds to give Blizzard the chance to catch up, and the profile data *should* be there and cached again.
