### ISSUE TITLE
Adding a region param returns 404

### ISSUE THREAD

**Issue by verath** [SunDwarf/OWAPI#37]
Adding a `region` parameter seems to always return 404.

For my profile: https://playoverwatch.com/en-us/career/pc/eu/Verath-2121
https://owapi.net/api/v2/u/Verath-2121/stats/general works
https://owapi.net/api/v2/u/Verath-2121/stats/general?platform=pc works
https://owapi.net/api/v2/u/Verath-2121/stats/general?region=eu does not
https://owapi.net/api/v2/u/Verath-2121/stats/general?platform=pc&region=eu does not

Looks like the issue is that the `B_PAGE_URL` pattern at [blizz_interface.py#L16](https://github.com/SunDwarf/OWAPI/blob/bb2d99bdd2557bd06f5a6313383894e5860b4f34/owapi/blizz_interface.py#L16) is missing a slash between platform and region?

**Comment by SunDwarf** [comment]
Whoops.
