### ISSUE TITLE
No support for xbox/psn

### ISSUE THREAD

**Issue by LawlyPopz** [SunDwarf/OWAPI#39]
xbox/psn as ?platform= does not work as it will still ass for a battle tag please fix this issue!

**Comment by SunDwarf** [comment]
what

show me the request you made

**Comment by Downy** [comment]
Your request should look like
https://owapi.net/api/v2/u/psnidhere/stats/general?platform=psn

**Comment by LawlyPopz** [comment]
https://owapi.net/api/v2/u/LittlejediWolf/stats/general?platform=xbox also ^^^ doesnt work

**Comment by SunDwarf** [comment]
Your profile doesn't exist.

**Comment by LawlyPopz** [comment]
https://overwatchtracker.com/profile/xbox/global/LittleJediWolf but it clearly does

**Comment by SunDwarf** [comment]
https://owapi.net/api/v2/u/LittleJediWolf/stats/general?platform=xbl

Capitalization is important.

**Comment by LawlyPopz** [comment]
oh the read me says XBOX not XBL

**Comment by SunDwarf** [comment]
b6c2428a8d52498600e05c4e135ab1d798d87824

**Comment by LawlyPopz** [comment]
Thanks you for the mega fast response <3
