### ISSUE TITLE
Live version down.

### ISSUE THREAD

**Issue by sirdoombox** [SunDwarf/OWAPI#4]
Whether or not this belongs here I don't know, but I've been using the live version succesfully for a while now with no issues, until today. All I can get from it are 500 errors whenever I attempt to request anything from it.

**Comment by SunDwarf** [comment]
MO is being cloudflare'd right now.

I can't exactly bypass cloudflare, so you'll have to wait until it stops.

**Comment by sirdoombox** [comment]
Ah yes, I hadn't taken the time to take a look through your code to check who you were using as your source to see if the issue was further up the chain. Apologies for the hasty issue report.

**Comment by SunDwarf** [comment]
Don't worry, I wouldn't have even noticed if not for this.

**Comment by SunDwarf** [comment]
Partially fixed - `/stats` now returns correct data.

**Comment by SunDwarf** [comment]
Heroes appears to be returning again, closing for now.

**Comment by imkimchi** [comment]
I have some questions about it. how could masteroverwatch get data that couldn't get from blizzard like player avater and something like it? we don't have any ways to get data without from blizzard?
