### ISSUE TITLE
Round or truncate floating point values

### ISSUE THREAD

**Issue by azah** [SunDwarf/OWAPI#40]
Example from `https://owapi.net/api/v2/u/LittleJediWolf/stats/general?platform=xbl`
```
"objective_time_avg": 0.006944444444444445,
"time_spent_on_fire_avg": 0.005277777777777778,
"time_spent_on_fire_most_in_game": 0.12555555555555556,
```

Maybe 3-4 decimal places?

**Comment by SunDwarf** [comment]
Personally I don't feel like this is an issue; they can always be truncated on the client end if need be. Otherwise this provides more accurate data, I guess?

Especially with edge cases such as times of under 1 seconds, which I have seen.

**Comment by azah** [comment]
That's true, it's up to you then. I can just implement it in my bot's logic
