### ISSUE TITLE
During an API call, the page keeps loading after showing data

### ISSUE THREAD

**Issue by phantium** [SunDwarf/OWAPI#57]
As of recent, when pulling the following URL in your browser (tested with latest Chrome and Firefox).. it keeps loading (Connecting...) a while longer after showing the JSON data:

E.g. https://owapi.net/api/v2/u/SunDwarf-21353/stats/general

This is causing my API calls to stop functioning, as it's expecting the page to stop transferring data.

![](http://i.raw.re/zc3MI)

**Comment by SunDwarf** [comment]
This is almost definitely a cloudflare issue.

I'll look into it.

**Comment by SunDwarf** [comment]
This should be resolved Soon™.

**Comment by phantium** [comment]
I can confirm it's good now, thanks! :+1:

**Comment by azah** [comment]
This can be closed now.
