### ISSUE TITLE
US based Battle.net accounts seem to always return '500'

### ISSUE THREAD

**Issue by Downy** [SunDwarf/OWAPI#6]
I've only tested a few cases but they all returned '500'.
Examples;
https://owapi.net/api/v1/u/Deemer-11363/stats
https://owapi.net/api/v1/u/xielle-1423/stats

**Comment by SunDwarf** [comment]
You can force the region with https://owapi.net/api/v1/u/Deemer-11363/stats?region=us, for example.

I'll look into it.

**Comment by SunDwarf** [comment]
Fixed by c9e77caf149fb6a0ef51c405e94d5fe5f7fd2db6.

**Comment by SunDwarf** [comment]
Okay, it's erroring seemingly at random now.

If you get a 500, I advise you to just try again - it should load properly the second time.  
Otherwise, force the region with `?region=code`.

**Comment by Downy** [comment]
Alright, better than nothing I suppose.
Thanks for the quick fix.

**Comment by imkimchi** [comment]
when returned 500, I tried again but i got same errors.

**Comment by Downy** [comment]
Yes, it's MasterOverwatch being cloudflared again.

**Comment by SunDwarf** [comment]
Alright, I've rolled out a better fix for this.

Routes on `/api/v1` return MasterOverwatch data.  
Routes on `/api/v2` return Blizzard data.

**Comment by imkimchi** [comment]
Oh god, It couldn't be fixed?

**Comment by imkimchi** [comment]
Alright. now i can get Blizzard data as well.
though i can't get the masteroverwatch data

**Comment by ccubed** [comment]
getting error 500'd on api/v2 as well. Setting region manually seems to resolve this.

**Comment by SunDwarf** [comment]
Fixed with the latest commit.
