### ISSUE TITLE
Make all responses JSON

### ISSUE THREAD

**Issue by chesterhow** [SunDwarf/OWAPI#66]
Currently, if the battle tag is valid, the content type of the response is `application/json`. Whereas if the battle tag is invalid, the content type of the response is `text/plain`. Is it possible for all responses to be JSON?

On a side note, really appreciate your work!

**Edit:** Or could you allow requests with headers to set `Content-Type: application/json`?

**Comment by SunDwarf** [comment]
Whoops, this was a slight oversight.

**Comment by SunDwarf** [comment]
Closed with the most recent commit.
