### ISSUE TITLE
Set 'Access-Control-Allow-Origin' in header

### ISSUE THREAD

**Issue by briva** [SunDwarf/OWAPI#69]
Firstly, thanks for your work.

I'm currently building a platform and I will use your project to get overwatch stats.

I got a little problem by a simple get call from my web app in ReactJS : No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.

Do you know how to set headers to : 'Access-Control-Allow-Origin' in asphat or kyoukai ?

Thx.

**Comment by SunDwarf** [comment]
It would be as simple as adding a line in `routes.py` - after line 77, with the content of `response.headers["Access-Control-Allow-Origin"] = "whatever"`.

**Comment by briva** [comment]
Awesome its working well.

Thanks for your reactivity @SunDwarf ;)
