### ISSUE TITLE
Currently erroring for people who have played new Comp

### ISSUE THREAD

**Issue by Js41637** [SunDwarf/OWAPI#70]
While I am sure this is only a temporary thing. API is currently erroring because Overwatch is currently not returning the amount of games played which is causing problemos.

Should be able to fix it by doing something like
```
g = game_box.xpath(".//text()[. = 'Games Played']/../..")
if not g:
    games, losses, wr = None, None, None
else:
    games = int(g[0][1].text.replace(",", ""))
    losses = games - wins
    wr = floor((wins / games) * 100)
```

**Comment by Js41637** [comment]
To clarify, anyone who has played Season 2 and has finished their placement matches, it stops returning the amount of games played and only returns the wins. Also for me most of the site is currently broken and behaving weirdly. I dunno wtf Blizzard are doing but, MasterOverwatch stats have pretty much completely broken without games played.

On a side note the new comp ranks seem to work properly and the same as they did before, its just a much larger number now.

**Comment by azah** [comment]
I'll take a look into this, thanks!

**Comment by SunDwarf** [comment]
Untested fix at 529874b76dffae57cb0bbb96c89933401bd478db. I haven't been able to repro this myself - it'd be great if somebody could verify this fixes it.

**Comment by SunDwarf** [comment]
Note that I haven't pushed it yet as I don't want anything to break.

**Comment by azah** [comment]
I don't know how to test this? I've played Season2 today, and
```
https://owapi.net/api/v2/u/Dad-12262/stats/general
```

```
https://owapi.net/api/v2/u/Dad-12262/stats/competitive
```

I would need an account that is causing errors.

**Comment by azah** [comment]
Okay, so it errors on 
```
https://owapi.net/api/v2/u/Solo-12577/stats/general
```,
but not 
```
https://owapi.net/api/v2/u/Solo-12577/stats/competitive
```

I'll test it real quick.

**Comment by azah** [comment]
@SunDwarf https://github.com/SunDwarf/OWAPI/commit/529874b76dffae57cb0bbb96c89933401bd478db works

**Comment by SunDwarf** [comment]
As much as I would like to, I literally can't do anything - the data just doesn't exist.

**Comment by azah** [comment]
Could it output None instead? I mean 0 could work.

**Comment by Js41637** [comment]
Yeah null would imply that we don't know instead of they have 0 games played

**Comment by SunDwarf** [comment]
I would, but this might break anyone who (correctly) assumes it is an int.

**Comment by azah** [comment]
Fair enough, 0 works.
