### ISSUE TITLE
Can't get ur Json response from JQuery Ajax Call : "Get No 'Access-Control-Allow-Origin' header is present on the requested resource"

### ISSUE THREAD

**Issue by quentinmeltzheim** [SunDwarf/OWAPI#71]
Hello, i tryed our Overwatch API and it work great. Nice job.
But when i tryed to import it into my web site, to add some content on the page, i get 
"No 'Access-Control-Allow-Origin' header is present on the requested resource". There is my code :
"
$.ajax({
                url: "http://owapi.net/api/v2/u/Neo-21849/stats/competitive",
                type: 'GET',
                crossDomain: true,
                dataType: 'json',
                success: function() { alert("Success"); },
                error: function (xhr, ajaxOptions, thrownError) {
                  alert(xhr.status);
                  alert(thrownError);
                }
            },function(data){
                console.log(data);
            });
".

If you have any idea to figure it out, it will be awesome ! :)

**Comment by azah** [comment]
See #69

**Comment by SunDwarf** [comment]
Should be fixed on the website.

**Comment by quentinmeltzheim** [comment]
Really awesome, thanks you so much ;)

**Comment by quentinmeltzheim** [comment]
That worked for a while ... But come back to the same prob 4 hours later ... Any idea ?

**Comment by SunDwarf** [comment]
I haven't changed anything.

**Comment by quentinmeltzheim** [comment]
![image](https://cloud.githubusercontent.com/assets/16000175/18227618/a4149492-722a-11e6-8460-eac0bd73970f.png)
I didn't change my code too :/ weird fact

**Comment by SunDwarf** [comment]
Use `https`.

**Comment by quentinmeltzheim** [comment]
--" this is that. Thx for quick answer. :D. Cya ;)
