### ISSUE TITLE
API v3

### ISSUE THREAD

**Issue by SunDwarf** [SunDwarf/OWAPI#72]
So I'm gonna be making a v3 to fix some issues v2 has (notably the region issues and the comp/qp split).  

(No, I'm not retiring v2 (yet)).

I'm looking on opinions on what to split and what to unify:

- Comp and quickplay together (i.e `{"competitive": ..., "quickplay": ...}`)  
- Heroes and other stats together

Basically, if it should be a giant JSON blob (easier) or multiple routes (pls senpai nginx can only take so much on an Atom).

**Comment by SunDwarf** [comment]
Oh yeah, this also means all 3 regions and 3 platforms will be available in one request, as well as taking shorter time due to fetching all regions in parallel.

**Comment by azah** [comment]
So v3 will keep the new `competitive: true` flag? Makes sense to cut down on the routes.

**Comment by Js41637** [comment]
I'd assume it will return both quickplay and competitive stats in the one request (if available) and return all hero stats on a `/heroes` route.

Regions (and platforms) make things a lot harder. That's up to 5 requests for a single user to try and find their location not to mention some users are on multiple regions.

**Comment by ifonefox** [comment]
>nginx can only take so much on an Atom
You're self-hosting this on a computer with an Atom Processor?

**Comment by SunDwarf** [comment]
```bash
eyes@veriny /v/w/owapi.net$ cat /proc/cpuinfo | grep "model name"
model name	: Intel(R) Atom(TM) CPU  C2750  @ 2.40GHz
model name	: Intel(R) Atom(TM) CPU  C2750  @ 2.40GHz
model name	: Intel(R) Atom(TM) CPU  C2750  @ 2.40GHz
model name	: Intel(R) Atom(TM) CPU  C2750  @ 2.40GHz
```

**Comment by RomainPln** [comment]
I agree all heroes stats together would help avoid 429 warnings.

**Comment by azah** [comment]
When is v3 going to be merged in?

**Comment by SunDwarf** [comment]
soontm

**Comment by azah** [comment]
I'm not sure how I can contribute to v3, but if there's something I can do just let me know.

**Comment by SunDwarf** [comment]
Well, I'm going to fix platforms and merge it to master tonight, then deploy it, so I need testers.
