### ISSUE TITLE
Returns Win rates Higher than 100%

### ISSUE THREAD

**Issue by ccubed** [SunDwarf/OWAPI#73]
Example Output for Matt-15211 at Heroes General
```
{
  "battletag": "Matt-15211",
  "_request": {
    "route": "/api/v2/u/Matt-15211/heroes/general",
    "api_ver": 2
  },
  "region": "us",
  "heroes": {
    "symmetra": 0.6333333333333333,
    "reinhardt": 2,
    "bastion": 0.7,
    "winston": 0.4,
    "pharah": 5,
    "lucio": 2,
    "soldier76": 3,
    "tracer": 8,
    "mercy": 0.65,
    "junkrat": 7,
    "mei": 6,
    "roadhog": 0.45,
    "mccree": 1,
    "zarya": 0.7666666666666667,
    "dva": 0.5833333333333334,
    "zenyatta": 1,
    "genji": 0.85,
    "hanzo": 3,
    "ana": 0.7833333333333333,
    "reaper": 0.7666666666666667,
    "torbjorn": 0.43333333333333335,
    "widowmaker": 1
  }
}
```

I took a look at the overwatch page. Tracer appears to be listing 0 games played, but that doesn't make sense given your code says to return 0 in that case. This may not be an issue with your code though is the point I'm making. I tested a couple other bots and they show 0 games played too for some reason. It doesn't seem to be a you problem, but I'll open it and you can decide what to do. At the least, not returning 0 seems like a problem.

**Comment by Js41637** [comment]
I'm not too sure what you mean by the example response, the heroes endpoint returns the amount of time played in hours so that result is correct?

Anyway, regarding games played, Blizzard removed the amount of games played from _some_ (most) users profile. Unfortunately without the amount of games played we cannot return the winrate, losses, or games.

**Comment by ccubed** [comment]
Ahh, @SunDwarf , Why you do dis to me. When did that change? Changed around to indicate time played then.
