### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by CptChaos** [SunDwarf/OWAPI#76]
The installation instructions on this package are failing on VM's I'm running (Debian Testing and Ubuntu 16.04).
Both VM's are running Python 3.5.2 and seem to fail to have ./venv/activate, which resides in venv/bin/activate. Running that file, it seems to install some things, but yet still does not compile, as it doesn't install every requirement.

I strongly suggest to make a better documentation, so other users can run this too on own computers / VM's.

**Comment by azah** [comment]
Post the error log please.

**Comment by CptChaos** [comment]
When I follow the installation guide step by step as it actually says, on step 3:
`source ./venv/activate && pip install -r requirements.txt`
I get `-bash: ./venv/activate: No such file or directory`

Which is obvious, as activate is in venv/bin/activate. When I go there manually and run it, I get

`Collecting Kyoukai==1.9.1 (from -r /opt/owapi/requirements.txt (line 1))
  Using cached Kyoukai-1.9.1-py3-none-any.whl
Collecting aioredis==0.2.8 (from -r /opt/owapi/requirements.txt (line 2))
  Using cached aioredis-0.2.8-py3-none-any.whl
Collecting aiohttp==0.22.5 (from -r /opt/owapi/requirements.txt (line 3))
  Using cached aiohttp-0.22.5-cp35-cp35m-manylinux1_x86_64.whl
Collecting asphalt==2.0.0 (from -r /opt/owapi/requirements.txt (line 4))
  Using cached asphalt-2.0.0-py3-none-any.whl
Collecting asphalt-redis==1.0.0 (from -r /opt/owapi/requirements.txt (line 5))
  Using cached asphalt_redis-1.0.0-py3-none-any.whl
Collecting asyncio-extras==1.1.1 (from -r /opt/owapi/requirements.txt (line 6))
  Using cached asyncio_extras-1.1.1-py3-none-any.whl
Collecting chardet==2.3.0 (from -r /opt/owapi/requirements.txt (line 7))
Collecting click==6.6 (from -r /opt/owapi/requirements.txt (line 8))
Collecting hiredis==0.2.0 (from -r /opt/owapi/requirements.txt (line 9))
Collecting http-parser==0.8.3 (from -r /opt/owapi/requirements.txt (line 10))
Collecting libmagic==1.0 (from -r /opt/owapi/requirements.txt (line 11))
Collecting lxml==3.6.1 (from -r /opt/owapi/requirements.txt (line 12))
  Using cached lxml-3.6.1.tar.gz
Collecting python-magic==0.4.12 (from -r /opt/owapi/requirements.txt (line 13))
Collecting PyYAML==3.11 (from -r /opt/owapi/requirements.txt (line 14))
Collecting redis==2.10.5 (from -r /opt/owapi/requirements.txt (line 15))
  Using cached redis-2.10.5-py2.py3-none-any.whl
Collecting typeguard==1.2.1 (from -r /opt/owapi/requirements.txt (line 16))
  Using cached typeguard-1.2.1-py3-none-any.whl
Collecting unidecode==0.04.19 (from -r /opt/owapi/requirements.txt (line 17))
Collecting Mako>=1.0.4 (from Kyoukai==1.9.1->-r /opt/owapi/requirements.txt (line 1))
Collecting httptools>=0.0.9 (from Kyoukai==1.9.1->-r /opt/owapi/requirements.txt (line 1))
Collecting werkzeug>=0.11.10 (from Kyoukai==1.9.1->-r /opt/owapi/requirements.txt (line 1))
  Using cached Werkzeug-0.11.11-py2.py3-none-any.whl
Collecting multidict<2,>=1.2.2 (from aiohttp==0.22.5->-r /opt/owapi/requirements.txt (line 3))
  Using cached multidict-1.2.2-cp35-cp35m-manylinux1_x86_64.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in /opt/venv/lib/python3.5/site-packages (from asphalt==2.0.0->-r /opt/owapi/requirements.txt (line 4))
Collecting MarkupSafe>=0.9.2 (from Mako>=1.0.4->Kyoukai==1.9.1->-r /opt/owapi/requirements.txt (line 1))
Building wheels for collected packages: lxml
  Running setup.py bdist_wheel for lxml ... error
  Complete output from command /opt/venv/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-scwbalbv/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmps7y72_i4pip-wheel- --python-tag cp35:
  Building lxml version 3.6.1.
  Building without Cython.
  ERROR: b'/bin/sh: 1: xslt-config: not found\n'
  ** make sure the development packages of libxml2 and libxslt are installed **

  Using build configuration of libxslt
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for lxml
  Running setup.py clean for lxml
Failed to build lxml
Installing collected packages: python-magic, click, PyYAML, asyncio-extras, typeguard, asphalt, MarkupSafe, Mako, httptools, werkzeug, Kyoukai, hiredis, aioredis, multidict, chardet, aiohttp, asphalt-redis, http-parser, libmagic, lxml, redis, unidecode
  Running setup.py install for lxml ... error
    Complete output from command /opt/venv/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-scwbalbv/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-vcdn84w8-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/venv/include/site/python3.5/lxml:
    Building lxml version 3.6.1.
    Building without Cython.
    ERROR: b'/bin/sh: 1: xslt-config: not found\n'
    ** make sure the development packages of libxml2 and libxslt are installed **

    Using build configuration of libxslt
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/lxml
    copying src/lxml/builder.py -> build/lib.linux-x86_64-3.5/lxml
    copying src/lxml/cssselect.py -> build/lib.linux-x86_64-3.5/lxml
    copying src/lxml/pyclasslookup.py -> build/lib.linux-x86_64-3.5/lxml
    copying src/lxml/usedoctest.py -> build/lib.linux-x86_64-3.5/lxml
    copying src/lxml/ElementInclude.py -> build/lib.linux-x86_64-3.5/lxml
    copying src/lxml/sax.py -> build/lib.linux-x86_64-3.5/lxml
    copying src/lxml/_elementpath.py -> build/lib.linux-x86_64-3.5/lxml
    copying src/lxml/__init__.py -> build/lib.linux-x86_64-3.5/lxml
    copying src/lxml/doctestcompare.py -> build/lib.linux-x86_64-3.5/lxml
    creating build/lib.linux-x86_64-3.5/lxml/includes
    copying src/lxml/includes/__init__.py -> build/lib.linux-x86_64-3.5/lxml/includes
    creating build/lib.linux-x86_64-3.5/lxml/html
    copying src/lxml/html/_html5builder.py -> build/lib.linux-x86_64-3.5/lxml/html
    copying src/lxml/html/builder.py -> build/lib.linux-x86_64-3.5/lxml/html
    copying src/lxml/html/html5parser.py -> build/lib.linux-x86_64-3.5/lxml/html
    copying src/lxml/html/_diffcommand.py -> build/lib.linux-x86_64-3.5/lxml/html
    copying src/lxml/html/clean.py -> build/lib.linux-x86_64-3.5/lxml/html
    copying src/lxml/html/formfill.py -> build/lib.linux-x86_64-3.5/lxml/html
    copying src/lxml/html/usedoctest.py -> build/lib.linux-x86_64-3.5/lxml/html
    copying src/lxml/html/_setmixin.py -> build/lib.linux-x86_64-3.5/lxml/html
    copying src/lxml/html/soupparser.py -> build/lib.linux-x86_64-3.5/lxml/html
    copying src/lxml/html/ElementSoup.py -> build/lib.linux-x86_64-3.5/lxml/html
    copying src/lxml/html/__init__.py -> build/lib.linux-x86_64-3.5/lxml/html
    copying src/lxml/html/defs.py -> build/lib.linux-x86_64-3.5/lxml/html
    copying src/lxml/html/diff.py -> build/lib.linux-x86_64-3.5/lxml/html
    creating build/lib.linux-x86_64-3.5/lxml/isoschematron
    copying src/lxml/isoschematron/__init__.py -> build/lib.linux-x86_64-3.5/lxml/isoschematron
    copying src/lxml/lxml.etree.h -> build/lib.linux-x86_64-3.5/lxml
    copying src/lxml/lxml.etree_api.h -> build/lib.linux-x86_64-3.5/lxml
    copying src/lxml/includes/relaxng.pxd -> build/lib.linux-x86_64-3.5/lxml/includes
    copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-x86_64-3.5/lxml/includes
    copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-x86_64-3.5/lxml/includes
    copying src/lxml/includes/c14n.pxd -> build/lib.linux-x86_64-3.5/lxml/includes
    copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-x86_64-3.5/lxml/includes
    copying src/lxml/includes/config.pxd -> build/lib.linux-x86_64-3.5/lxml/includes
    copying src/lxml/includes/schematron.pxd -> build/lib.linux-x86_64-3.5/lxml/includes
    copying src/lxml/includes/xpath.pxd -> build/lib.linux-x86_64-3.5/lxml/includes
    copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-x86_64-3.5/lxml/includes
    copying src/lxml/includes/tree.pxd -> build/lib.linux-x86_64-3.5/lxml/includes
    copying src/lxml/includes/xslt.pxd -> build/lib.linux-x86_64-3.5/lxml/includes
    copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-x86_64-3.5/lxml/includes
    copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-x86_64-3.5/lxml/includes
    copying src/lxml/includes/uri.pxd -> build/lib.linux-x86_64-3.5/lxml/includes
    copying src/lxml/includes/xinclude.pxd -> build/lib.linux-x86_64-3.5/lxml/includes
    copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-3.5/lxml/includes
    copying src/lxml/includes/etree_defs.h -> build/lib.linux-x86_64-3.5/lxml/includes
    creating build/lib.linux-x86_64-3.5/lxml/isoschematron/resources
    creating build/lib.linux-x86_64-3.5/lxml/isoschematron/resources/rng
    copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-x86_64-3.5/lxml/isoschematron/resources/rng
    creating build/lib.linux-x86_64-3.5/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-x86_64-3.5/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-x86_64-3.5/lxml/isoschematron/resources/xsl
    creating build/lib.linux-x86_64-3.5/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-x86_64-3.5/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-x86_64-3.5/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-x86_64-3.5/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-x86_64-3.5/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-x86_64-3.5/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-x86_64-3.5/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    running build_ext
    building 'lxml.etree' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/src
    creating build/temp.linux-x86_64-3.5/src/lxml
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/home/packages/python/3.5/python3.5-3.5.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Isrc/lxml/includes -I/opt/venv/include -I/usr/include/python3.5m -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-3.5/src/lxml/lxml.etree.o -w
    In file included from src/lxml/lxml.etree.c:320:0:
    src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: No such file or directory
     #include "libxml/xmlversion.h"
                                   ^
    compilation terminated.
    Compile failed: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    creating tmp
    cc -I/usr/include/libxml2 -c /tmp/xmlXPathInitw5ophi9w.c -o tmp/xmlXPathInitw5ophi9w.o
    /tmp/xmlXPathInitw5ophi9w.c:1:26: fatal error: libxml/xpath.h: No such file or directory
     #include "libxml/xpath.h"
                              ^
    compilation terminated.
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    *********************************************************************************
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/opt/venv/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-scwbalbv/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-vcdn84w8-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/venv/include/site/python3.5/lxml" failed with error code 1 in /tmp/pip-build-scwbalbv/lxml/`

**Comment by CptChaos** [comment]
I tried with the super basic knowledge of Python that I have to install any missing packages, such as python-libxml2 and python3-libxml2, but to no avail at all, the error remains the same.

**Comment by azah** [comment]
have you tried installing through python's pip module? `python -m pip install xx`

**Comment by CptChaos** [comment]
How are the packets called when I install through pip/pip3?

**Comment by azah** [comment]
It's a module in python 3 only I believe.

**Comment by SunDwarf** [comment]
1) why are you running this as root jesus fuck

2)   ** make sure the development packages of libxml2 and libxslt are installed **

**Comment by azah** [comment]
Ah yes that's really dangerous, have you been running all the install commands as root?

**Comment by CptChaos** [comment]
I am installing the packages as root indeed, but that shouldn't make a difference if I'd switch to a user with lower privileges... No one said I'll be running as root eventually... ;)
Both libxml2 and libxslt (for both Python as Python 3) are already installed.

**Comment by SunDwarf** [comment]
Evidently not because the build error shows they're not

Install the libs and dev headers not the python modules

**Comment by CptChaos** [comment]
Yep, it's evidently not installed... How come console says this when I try to install them:

`python-lxml is already the newest version (3.6.4-1).
python3-lxml is already the newest version (3.6.4-1).
python-libxml2 is already the newest version (2.9.4+dfsg1-1+b1).
`

**Comment by SunDwarf** [comment]
You need to install libxlst-dev or whatever not the packages

**Comment by CptChaos** [comment]
Just installed libxslt-dev, seems to build something now. Got an error `Failed building wheel for lxml`, shouldn't that be a problem?

**Comment by SunDwarf** [comment]
no

**Comment by CptChaos** [comment]
Hmmm, when I try to boot it, by running `asphalt run config.yml` (just to test), I get this error:

`
Traceback (most recent call last):
  File "/opt/owapi/venv/bin/asphalt", line 11, in <module>
    sys.exit(main())
  File "/opt/owapi/venv/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/opt/owapi/venv/lib/python3.5/site-packages/click/core.py", line 675, in main
    _verify_python3_env()
  File "/opt/owapi/venv/lib/python3.5/site-packages/click/_unicodefun.py", line 119, in _verify_python3_env
    'mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Either run this under Python 2 or consult http://click.pocoo.org/python3/ for mitigation steps.

This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
`

**Comment by SunDwarf** [comment]
did you read the error

**Comment by CptChaos** [comment]
I am not a Python programmer at all. So yes, I did read the error, but that doesn't say I know what to do...

**Comment by SunDwarf** [comment]
![https://i.imgur.com/aVzFa7h.png](https://i.imgur.com/aVzFa7h.png)

**Comment by CptChaos** [comment]
I did the exports, but still get errors booting:
```
Traceback (most recent call last):
  File "/opt/owapi/venv/bin/asphalt", line 11, in <module>
    sys.exit(main())
  File "/opt/owapi/venv/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/opt/owapi/venv/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/opt/owapi/venv/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/owapi/venv/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/owapi/venv/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/opt/owapi/venv/lib/python3.5/site-packages/asphalt/core/command.py", line 36, in run
    component = component_types.create_object(**component_config)
  File "/opt/owapi/venv/lib/python3.5/site-packages/asphalt/core/util.py", line 146, in create_object
    plugin_class = self.resolve(type)
  File "/opt/owapi/venv/lib/python3.5/site-packages/asphalt/core/util.py", line 120, in resolve
    return resolve_reference(obj)
  File "/opt/owapi/venv/lib/python3.5/site-packages/asphalt/core/util.py", line 33, in resolve_reference
    'error resolving reference {}: could not import module'.format(ref)) from e
LookupError: error resolving reference owapi.app:APIComponent: could not import module
```

**Comment by SunDwarf** [comment]
`PYTHONPATH=. asphalt run config.yml`

**Comment by CptChaos** [comment]
Works now. :) Thanks for the help, guys! I wouldn't be able to find the missing packages (libxslt-dev for Debian Testing). So if the installation notes would mention about that, I guess more people are able to run their own version of this great API tool!

**Comment by CptChaos** [comment]
I found another few required packages for the speedboost; uvloop and unidecode are needed, which can be installed by using pip(3). :)

**Comment by azah** [comment]
FYI in the future please learn to google for errors/info and such. 99% of the time it'll already be covered.

And don't run things as root unless you have a very strong reason.

**Comment by CptChaos** [comment]
Which is why I created the issue. I couldn't find the answer, I am not a Python programmer, so I did not "see" I was still missing a package. The documentation was also lacking. If it had a proper requirements section, I should'nt have to make this issue at all. ;)
