### ISSUE TITLE
v3/blob returns null for all regions

### ISSUE THREAD

**Issue by azah** [SunDwarf/OWAPI#79]
`http://localhost:4444/api/v3/u/Aurelius-1648/blob`

Actually every v3 route returns the following:

**Output:**
```
{
    "_request": {
        "api_ver": 3,
        "route": "/api/v3/u/Aurelius-1648/blob"
    },
    "eu": null,
    "kr": null,
    "any": null,
    "us": null
}
```

**Comment by azah** [comment]
Ok, I see now that you need to add `?platform=x`.
So is this required for v3 now? It won't check through the 3 platforms automatically?

**Comment by SunDwarf** [comment]
It... should do?

**Comment by SunDwarf** [comment]
Probably just a change from `platform=ctx.request.args.get("platform")` to `platform=ctx.request.args.get("platform", "pc")`. Free PR if anyone wants it before I fix it.
