### ISSUE TITLE
v3 Hero stats giving "s76" and "soldier76"

### ISSUE THREAD

**Issue by mikevb1** [SunDwarf/OWAPI#81]
These are returned at `[REGION]["heroes"]["stats"]["quickplay"/"competitive"]["s76"/"soldier76"]`

Can be found in quickplay and competitive stats, s76 and soldier76 have the exact same stats, just in different keys.

Checked [the divs](https://github.com/SunDwarf/OWAPI/blob/master/owapi/v3/parsing.py#L30) after posting this. This seems intentional, as dva comes up as d.va as well. I guess this can be closed if this is for backwards compatibility or whatever.

**Comment by SunDwarf** [comment]
They were a relic copied over from v2, and probably aren't needed in the new version.

I've removed them for v3 only now.
