### ISSUE TITLE
Multiple "overwatch.guid.0x..."

### ISSUE THREAD

**Issue by mikevb1** [SunDwarf/OWAPI#82]
Not sure if these are planned to be supported or not, but a small report:

overwatch.guid.0x0860000000000030 - float, 742.0
overwatch.guid.0x0860000000000031 - float, 264.0
overwatch.guid.0x0860000000000033 - float, 76.0
overwatch.guid.0x08600000000001bb - str, "23%" 
overwatch.guid.0x0860000000000216 - float, 10.0 (ana/widow [hero_stats])
overwatch.guid.0x0860000000000217 - float, 30.0 (ana/widow [hero_stats])
overwatch.guid.0x086000000000022f - float, 3896.0 (only under zarya [hero_stats])
overwatch.guid.0x0860000000000230 - float, 33600.0 (only under zarya [hero_stats])
overwatch.guid.0x08600000000002ff - float, 2.0 (only under genji [hero_stats])
overwatch.guid.0x086000000000033d - float, 2.0
overwatch.guid.0x08600000000003e4 - float, 0.04
overwatch.guid.0x08600000000003e8 - float, 1.24
overwatch.guid.0x08600000000003f7 - float, 1470.0
overwatch.guid.0x08600000000003f8 - float, 1698.0
overwatch.guid.0x086000000000040f - float, 380.0 (only ana)
overwatch.guid.0x0860000000000410 - float, 169.0 (only ana)
overwatch.guid.0x086000000000042e - float, 3.0 (only under [stats][competitive][game_stats])
overwatch.guid.0x0860000000000430 - float, 2.0

[blob.json](https://github.com/SunDwarf/OWAPI/files/477999/blob.txt) for reference

**Comment by SunDwarf** [comment]
I unfortunately have no idea what these are; presumably an error on blizzard side as I've noticed them on the actual website before.

I'm also not sure if I should keep them or not because they do seem to be stats, just without names.

**Comment by Js41637** [comment]
Yes these are errors, I've had them on the site for almost 3 weeks now, Blizzard don't seem to give a single fuck about their website.
