### ISSUE TITLE
API v2 Deprecation Notice

### ISSUE THREAD

**Issue by SunDwarf** [SunDwarf/OWAPI#84]
As a new version comes, the old version must go eventually.  
That is why I have officially decided that **API v2 is deprecated.**  

It will be supported until **_31st December 2016**_, at which point I won't care anymore, and will stay broken until a Blizzard change makes it completely unusuable.

This gives just over 3 months to change (which is about the time this project has existed).

**Comment by azah** [comment]
👍

**Comment by SunDwarf** [comment]
:bell: :bell: :bell: 

The deadline is coming up! If V2 breaks at any point after midnight on the 1st of Janurary 2017, it won't be fixed.

**Comment by SunDwarf** [comment]
![image](https://cloud.githubusercontent.com/assets/8783751/21574090/cc1087b4-cee4-11e6-99bf-230fce9eeaa5.png)
