### ISSUE TITLE
Can not get "cn" data

### ISSUE THREAD

**Issue by zhs2472** [SunDwarf/OWAPI#9]
https://owapi.net/api/v1/u/Song-5702/stats
It's my character and it shows "profile not found".
Then I tried some other accounts in "cn". I got the same result.

**Comment by SunDwarf** [comment]
This must be a new region that was added recently - when I first wrote it, the region didn't exist.

I'll add the support for CN regions in a bit.

**Comment by zhs2472** [comment]
Thanks very much.

**Comment by ACmagic** [comment]
the problem remains unsolved.

**Comment by Dam720** [comment]
Do you have an example of Battle Tag from cn who doesn't work ? Its seems like Song doesn't exist on playoverwatch or MasterOverwatch ...

**Comment by SunDwarf** [comment]
This is not an OWAPI issue - the data sources simply do not exist.

If you can link me to the playoverwatch page, then I can actually check it and fix it.

**Comment by ACmagic** [comment]
@SunDwarf  please find my own [playoverwatch](https://playoverwatch.com/en-us/career/pc/cn/dudubirdie-5198) for your reference.

**Comment by SunDwarf** [comment]
That page too returns a 404 error.

It seems as if the data for china is on an entirely separate domain to the rest, and I don't know where to find player data there.

**Comment by ACmagic** [comment]
@SunDwarf Been there...The server is unstable...You need to reload the page a few times to get the play data.

**Comment by zhs2472** [comment]
@SunDwarf This is my character on  masteroverwatch http://masteroverwatch.com/profile/pc/cn/Song-5702
