### ISSUE TITLE
Problem install on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by briva** [SunDwarf/OWAPI#91]
Hello,

Lxml will never finish building on ubuntu :

source ./venv/bin/activate && pip install wheel && pip install -r requirements.txt =>

> Collecting MarkupSafe>=0.9.2 (from Mako>=1.0.4->Kyoukai==1.9.2.1->-r requirements.txt (line 1))
> Building wheels for collected packages: lxml
>   Running setup.py bdist_wheel for lxml ... -

Locked.

**Comment by SunDwarf** [comment]
ok
