### ISSUE TITLE
API returns HTTP/400 error when using PHP, the same URL returns HTTP/200 when using a browser

### ISSUE THREAD

**Issue by CptChaos** [SunDwarf/OWAPI#96]
Hi there,

I think there's something with the API; when I do a request with PHP (with both curl as file_get_contents), the request doesn't get a correct reply. The reply I get is a HTTP/400 error (Bad Request). 
I get this error on both API's; on https://owapi.net as do I get the error on my local machine.

When I open the same URL (for both api's) in a new tab of my browser, I get a HTTP/200 and thus a reply.

So I am wondering what I am missing, should I send a header along? If so, which one?

**Comment by SunDwarf** [comment]
Is this for v3? If so, change your User-Agent header.

**Comment by CptChaos** [comment]
Yes, this is for v3, sorry, I forgot to mention that.

I've also added a User-Agent header with the request with cURL, but also got a HTTP 400 error in return.

**Comment by SunDwarf** [comment]
Well, you just sent it as a URL parameter, not as a header.

**Comment by CptChaos** [comment]
I don't get why I have to set the User-Agent through a URL parameter (and what parameter would I need for it?) where it normally is a header?

**Comment by SunDwarf** [comment]
You didn't set it as a header, you set it as a URL param, somehow.

`[30/Sep/2016:23:21:48 +0100] "GET /api/v3/u/CptChaos-2957/blob?User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%3B+rv%3A49.0%29+Gecko%2F20100101+Firefox%2F49.0 HTTP/1.1" 400 182 "-" "-"
`

**Comment by CptChaos** [comment]
Hmmm, weird. I'll check it out.

**Comment by CptChaos** [comment]
Thanks, that fixed it! :)
