### ISSUE TITLE
user agent issue

### ISSUE THREAD

**Issue by Crytek** [SunDwarf/OWAPI#97]
Hey
I am getting this error: "i! To prevent abuse of this service, it is required that you customize your user agent."

I am using cURL to get the data. can you help me resolve this issue?

**Comment by SunDwarf** [comment]
The cURL library or the cURL client?

**Comment by Crytek** [comment]
this is the code we are using to send the request:

```
$ch = curl_init("https://owapi.net/api/v3/u/Shadowbar-2251/heroes/competitive");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_BINARYTRANSFER, true);
$content = curl_exec($ch);
curl_close($ch);
```

**Comment by SunDwarf** [comment]
Use `curl_setopt($curl, CURLOPT_USERAGENT, $agent);` where `$agent` is your custom user agent (something identifyable).
